- src/App.js
- src/libs/intents/localMethods.ts
- src/screens/home/components/HomeView.js
- src/screens/lock/functions/lockScreenFunctions.ts
- src/screens/lock/hooks/useLockScreen.ts
- Delete data on logout
- Show splashcreen on wake up
- Show splashscreen on boot
- Show lockscreen on boot
> fix: Improve lock/unlock states

- connectors/totalenergies/src/index.js
> fix: Fixing some selectors

- src/screens/lock/LockScreen.tsx
- src/ui/TextField/styles.ts
Font size, font family, keyboard behaviour
> fix: add style improvements

- src/App.js
- src/screens/lock/functions/lockScreenFunctions.ts
- src/screens/lock/hooks/useLockScreen.ts
- src/ui/Container/index.tsx
- src/ui/Tooltip/styles.ts
This PR handles multiple fixes, each one is described in its own commit, so feel free to check commit messages for more details.
> Fix: Biometry fixes for iOS

- android/app/src/main/AndroidManifest.xml
- src/libs/functions/urlHelpers.js
Please refer to each commit for fix description
> fix: reviewing sentry errors

- src/libs/intents/setFlagshipUI.ts
ChangeBarColors() change both StatusBar and NavigationBar
so we need to check if we need to change the StatusBar
if the StatusBar should be different from the NavigationBar.
> feat: allow decoupled changeBarColors

- .gitignore
Some systems seem to have an issue with this package, but not the CI.
Best way is to update the gitignore file,
so it keeps the repo clean but also indicates there's an issue with this lib
> chore: add local patch to gitignore

- src/libs/connectorLibs/saveFiles.js
This PR remove statByPath of cozy-client-js and use new cozy client.
Aim to be stacked with  : https://github.com/cozy/cozy-flagship-app/pull/555
> feat: Remove cozy-client-js from statByPath function

- src/libs/connectorLibs/saveFiles.js
This PR remove create of cozy-client-js and use new cozy client.
Aim to be stacked with : https://github.com/cozy/cozy-flagship-app/pull/555
> feat: Remove cozy-client-js when creating or updating file

- connectors/connectorLibs/ContentScript.js
- connectors/connectorLibs/ContentScript.spec.js
Adding a function to normalize filename in the ContentScript for downloaded konnector's files
> feat: Adding filename normalizer function

- package.json
- scripts/tsconfig.json
- tsconfig.json
- yarn.lock
Use the global Cozy config instead of a custom one.
Still keep alias as custom option
> feat: use cozy-tsconfig

- README.md
Just to help new developer to start correctly on Android.
> docs: Add variant in yarn android command

- src/libs/Launcher.js
Use new call to download file in konnectors.
This call is implemented in cozy-clisk in https://github.com/konnectors/libs/pull/920
We will need konnectors up to date (contentScript from clisk) when using this in flagship app.
> feat: Download files from konnectors in worker

- src/components/getLocalFonts.ts
- src/components/makeErrorPage.js
- src/components/makeHTML.js
- src/screens/error/ErrorScreen.tsx
- src/screens/welcome/WelcomeScreen.jsx
Using fonts from device instead of user instance on unlogged (or potentially unlogged) views.
Inspired from this SO post https://stackoverflow.com/a/67409099/4817704
> fix: use local fonts in html webviews

- CODEOWNERS
- codeowners updated to flagship devs
> doc: update codeowners

- package.json
- yarn.lock
> fix: Fixing metadata deduplication by upgrading cozy-clisk

- src/libs/functions/getOnboardingDataFromRequest.js
- src/libs/functions/getOnboardingDataFromRequest.spec.js
- src/screens/login/components/ClouderyCreateInstanceView.js
- src/screens/login/components/OidcOnboardingView.tsx
- src/screens/login/components/functions/oidc.spec.js
- src/screens/login/components/functions/oidc.ts
This PR handle new OIDC redirection links from latest Cloudery changes
All commits contain their own description with context so feel free to review commit by commit
> feat: Handle new redirection URL type in ClouderyCreateInstanceView and OidcOnboardingView

- src/libs/ReactNativeLauncher.js
- src/libs/ReactNativeLauncher.spec.js
Now the pilot will need the current account to know what to do in ensureAuthenticated
If there is no account or if there is an account
> feat: Pass account to pilot.ensureAuthenticated

- ios/Podfile.lock
> fix: Regenerate Podfile

- src/components/webviews/CryptoWebView/jsInteractions/jsFunctions/jsComputePass.js
I encountered this line this week and I suppose it is a typo ?
> fix: computePAss typo

- __tests__/jest.config.js
- package.json
- yarn.lock
To fix a bug of duplication of saved identities
See https://github.com/konnectors/libs/pull/943
> feat: Update cozy-clisk to 0.12.2     

- README.md
- package.json
4 improvement propositions from the setup from @Merkur39 
Tell me what you think :)
> Improve newcomers setup

- __tests__/jestSetupFile.js
- src/app/view/Secure/PasswordPrompt.spec.tsx
- src/app/view/Secure/PasswordPrompt.tsx
- src/app/view/Secure/PinPrompt.spec.tsx
- src/app/view/Secure/PinPrompt.tsx
- src/app/view/Secure/SetPinView.spec.tsx
- src/app/view/Secure/hooks/usePasswordPrompt.ts
- src/app/view/Secure/hooks/usePinPrompt.ts
This PR includes refactoring of the `PasswordPrompt` and `PinPrompt` components to separate out logic into hooks and improve the testing strategy. It introduces a set of unit tests to ensure these components behave as expected.
The `PasswordPrompt` and `PinPrompt` components have been refactored to separate the business logic out into hooks (`usePasswordPrompt` and `usePinPrompt`). This makes the components easier to reason about and maintain. The components are now mainly responsible for rendering, while the hooks handle the business logic and side-effects, such as navigation.
Unit tests have been introduced for the `PasswordPrompt` and `PinPrompt` components. The tests verify that the components render as expected and navigate to the correct routes when the user interacts with them. The …
> fix: improve handling of SecurePrompt views

- src/hooks/useAppBootstrap.js
On current implementation, when the app is already opened and when the user clicks on a Login, MagicLink or Onboarding deep links, then the user is redirected to the corresponding view without any additional check
This is problematic when the user is already connected because we don't want them to loose their session
This can happen if the user log-in to the app using an email link and then they click again on the email link. In this situation we want the link to do nothing
To fix this we chose to interpret login related links only if no user session is detected
> fix: Do not handle login related deep links if a user is connected

- CHANGELOG.md
- android/app/build.gradle
- ios/CozyReactNative/Info.plist
- package.json
> feat: Bump app version to 1.1.9

- CHANGELOG.md
- android/app/build.gradle
- ios/CozyReactNative/Info.plist
- package.json
> feat: Bump app version to 1.1.10

- __tests__/jestSetupFile.js
- ios/Podfile.lock
- package.json
- patches/@react-native-camera-roll+camera-roll+5.7.2.patch
- src/@types/cozy-client.d.ts
- src/app/domain/backup/models/Album.ts
- src/app/domain/backup/models/Backup.ts
- src/app/domain/backup/models/Media.ts
- src/app/domain/backup/models/index.ts
- src/app/domain/backup/services/getMedias.ts
- src/app/domain/backup/services/manageAlbums.ts
- src/app/domain/backup/services/manageBackup.ts
- src/app/domain/backup/services/manageLocalBackupConfig.ts
- src/app/domain/backup/services/managePermissions.ts
- src/app/domain/backup/services/manageProgress.ts
- src/app/domain/backup/services/manageRemoteBackupConfig.spec.ts
- src/app/domain/backup/services/manageRemoteBackupConfig.ts
- src/app/domain/backup/services/uploadMedia.android.ts
- src/app/domain/backup/services/uploadMedia.ios.ts
- src/app/domain/backup/services/uploadMedias.ts
- src/app/domain/nativePermissions/index.ts
- src/app/domain/nativePermissions/models/index.ts
- src/app/domain/nativePermissions/services/nativePermissions.ts
- src/components/webviews/jsInteractions/jsCozyInjection.js
- src/libs/intents/localMethods.ts
- yarn.lock
- Manage permissions for backup (check permissions, ask permissions, open settings)
- Use cozy-intent to send backup progress to frontends
- Upload video for Live Photo
- Manage albums (create, add photo in album, ...)
To do :
> New backup : permission, progress update, Live Photo, albums

- src/app/domain/backup/models/Backup.ts
- src/app/domain/backup/services/manageBackup.ts
Allow front end to go to backup folder
> feat(backup): getBackupInfo return remoteBackupConfig

- transifex.yml
Adding transifex yaml config so the synchronization can happen through github integration.
Already configured transifex side
> feat: add transifex config

- .github/workflows/build-android-dev.yml
- .github/workflows/build-android-prod.yml
- android/build.gradle
chore: Update buildToolsVersion to 33.0.0
chore: Fix Android Build Tools issue
> Fix Android Build Tools issue

- android/app/src/main/java/io/cozy/flagship/mobile/MainActivitycozy.java
- android/app/src/main/java/io/cozy/flagship/mobile/MainActivitymabulle.java
- android/app/src/main/java/io/cozy/flagship/mobile/MainActivitymespapiers.java
- src/app/domain/backup/services/manageBackup.ts
- src/libs/notifications/notifications.spec.ts
- src/libs/notifications/notifications.ts
Open flagship app and redirect to cozy app when opening local notification
> Open flagship app and redirect to cozy app when opening local notification

- README.md
> docs: Add reset-android script to README

- src/app/domain/backup/models/Backup.ts
- src/app/domain/backup/services/getMedias.ts
- src/app/domain/backup/services/manageBackup.ts
Send number of medias loaded from native side to front end to display it. See https://github.com/cozy/cozy-drive/pull/2982.
> Backup performance

- .github/workflows/build-ios-dev.yml
- .github/workflows/build-ios-prod.yml
- .github/workflows/quality_checks.yml
This would homogenise workflows and jobs names
> Chore: Rename CI workflows and jobs

- android/app/src/dev/google-services.json
- android/app/src/prod/google-services.json
- white_label/brands/cozy/android/app/src/dev/google-services.json
- white_label/brands/cozy/android/app/src/prod/google-services.json
- white_label/brands/mabulle/android/app/src/dev/google-services.json
- white_label/brands/mabulle/android/app/src/prod/google-services.json
- white_label/brands/mabulle/ios/Dev/GoogleService-Info.plist
- white_label/brands/mabulle/ios/Prod/GoogleService-Info.plist
> feat: Set final google service configuration for MaBulle

- white_label/brands/mabulle/android/app/brand.gradle
- white_label/brands/mabulle/ios/CozyReactNative/CozyReactNative.entitlements
- white_label/brands/mabulle/js/constants/strings.json
Corresponding .well-known files have been declared in the registry config
> feat: Set final universal link url for MaBulle

- package.json
- src/app/domain/backup/helpers/media.spec.ts
- src/app/domain/backup/helpers/media.ts
- src/app/domain/backup/services/manageLocalBackupConfig.ts
- src/app/domain/backup/services/uploadMedia.ios.ts
- src/app/domain/backup/services/uploadMedias.ts
- src/app/domain/upload/models/index.ts
- src/app/domain/upload/services/index.ts
- src/app/domain/upload/services/upload.android.ts
- src/app/domain/upload/services/upload.ios.ts
- src/libs/monitoring/Sentry.ts
- src/libs/monitoring/grouping.ts
- yarn.lock
Fix some backup issues about media comparison and error logging.
> Backup fixes 

- src/libs/ReactNativeLauncher.js
- src/screens/konnectors/LauncherView.js
- src/screens/konnectors/LauncherView.spec.jsx
> feat: Log the finally installed clisk konnector version

- src/libs/ReactNativeLauncher.js
This is a draft. Probably the way to package the trace is not the best, but the data is very useful. Please comment this.
This will save some useful debug data :
- current url on worker
- current stringified dom on worker
- all the console.log in pilot and worker
In a trace file in the form : `trace_<date>_<slug>_<accountId>.html`
Under the following conditions :
- if the debug.clisk.html-on-error flag is set to true
- if the konnector throws an error
This way, the user has the possibility to inspect the data sent to the
cozy team before sharing it with a member of the cozy team.
Here is the resulting file format :
```html
<html>
...current worker page html
</html>
> feat: Fetch and save debug data on konnector errors

- src/app/domain/backup/helpers/error.ts
- src/app/domain/backup/services/manageBackup.ts
- src/app/domain/backup/services/uploadMedias.ts
Fix some minor issues about error message in backup
> Missing backup error message

- ios/Podfile.lock
- package.json
- yarn.lock
> Update some deps

- src/app/view/Secure/SetPinView.tsx
- src/ui/Button/index.tsx
- src/ui/Button/styles.ts
- src/ui/Typography/index.tsx
- src/ui/Typography/styles.ts
This reverts commit b11fb15cef68cc8b5cb9205dd8854b398f9f85b0
This commit collides with the CozyThem PR implementation. The easiest way to handle conflicts is to revert this commit and to reapply the disable condition for the SetPinView button
Related PR: #1062
> revert: handle disabled button styles"

- package.json
- yarn.lock
To get the new forceReplaceFile saveFiles entry attribute
> feat: Upgrade cozy-clisk to 0.30.0

- white_label/brands/mabulle/js/constants/extra-strings.json
> feat: rename universal links for mabulle

- src/app/view/Lock/LockScreen.tsx
> [VIO-114] Add autoFocus on LockScreen text inputs

- src/app/domain/geolocation/tracking/consts.js
- src/app/domain/geolocation/tracking/index.js
- src/app/domain/geolocation/tracking/tracking.js
Several actions to reduce battery impact:
- Do not start tracking when already started
- Ignore "still" activities with low confidence : iOS can produce a lot of them
- Remove extra logs
> [DAT-23] Geoloc battery

- README.md
Add install steps, clarify sections and add common errors
> docs: Improve install doc

- src/app/domain/geolocation/helpers/quota.ts
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
Duplicate since it will be done on coachco2 side with a service.
> feat: Do not send a notification when checking geolocation quota

- src/app/domain/backup/services/manageBackup.ts
```
* Do not go to sleep during backup preparation
```
> Do not go to sleep during backup preparation

- package.json
- yarn.lock
```
*
*
* Update cozy-client and react-native-gzip
```
> feat: Update package needed for RN0.72

- src/app/domain/iap/services/clouderyOffer.ts
- src/app/domain/limits/OauthClientsLimitService.ts
* Let the user open a help link in the device's browser when max devices reached
> feat: handle help link in max devices in paywall (VO-640)

- src/constants/strings.json
- src/locales/i18n.ts
- src/locales/useInitI18n.ts
- white_label/brands/cozy/js/constants/extra-strings.json
- white_label/brands/mabulle/js/constants/extra-strings.json
> feat: use FR as default locale for GL (VO-693)

- android/app/src/main/res/values/styles.xml
- src/app/theme/themeManager.ts
- src/components/webviews/CozyProxyWebView.js
- src/screens/cozy-app/CozyAppScreen.Animation.tsx
- src/screens/cozy-app/CozyAppScreen.functions.ts
- src/screens/cozy-app/CozyAppScreen.styles.ts
- src/screens/cozy-app/CozyAppScreen.tsx
- src/ui/colors.ts
```
* Dark mode on flagship app
```
> Dark mode on flagship app

- src/app/theme/colorScheme.ts
- src/app/theme/themeManager.ts
- src/screens/cozy-app/CozyAppScreen.Animation.tsx
- src/screens/cozy-app/CozyAppScreen.functions.ts
- src/screens/cozy-app/CozyAppScreen.styles.ts
- src/screens/cozy-app/CozyAppScreen.tsx
- src/ui/CozyTheme/CozyTheme.tsx
- src/ui/colors.ts
> Dark mode behind flag

- __mocks__/react-native-inappbrowser-reborn-mock.ts
- __tests__/jestSetupFile.js
- package.json
- src/App.js
- src/app/theme/colorScheme.ts
- src/libs/httpserver/indexGenerator.spec.js
- src/libs/intents/localMethods.ts
- yarn.lock
Allow to support dark mode and light mode.
```
* Support custom color scheme
*
*
```
> Support custom color scheme in flagship app

- android/build.gradle
- ios/Podfile.lock
- package.json
- yarn.lock
```
*
*
* Target Android API 34
```
> Target Android API 34

- src/components/Bar.tsx
- src/screens/cozy-app/CozyAppScreen.Animation.tsx
- src/screens/cozy-app/CozyAppScreen.functions.ts
```
*
* 
* Fix progress bar color in dark mode
```
> Fix progress bar color in dark mode

- src/app/theme/colorScheme.ts
- white_label/brands/cozy/js/ui/colors.ts
- white_label/brands/mabulle/js/ui/colors.ts
- white_label/tsconfig.json
```
*
* Dark mode colors
* Crash at log out due to useColorScheme 
*
```
> Fix dark mode colors + log out

- src/constants/strings.json
> fix: Remove empty space in strings.json

- package.json
- yarn.lock
```
* Do not download the same file multiple times when multiple bills are related to the same file
```
> feat: Upgrade cozy-clisk to 0.38.1

- src/@types/cozy-client.d.ts
To handle JobCollection create and waitFor methods
> fix: CozyClient collection type

- CHANGELOG.md
- android/app/build.gradle
- ios/CozyReactNative/Info.plist
- package.json
> feat: Bump app version to 1.1.31

- package.json
- src/app/domain/performances/sendPerformancesByEmail.ts
- src/pouchdb/sendDbByEmail.ts
- yarn.lock
See https://github.com/cozy/cozy-client/pull/1579/commits/a9e8784420da9a04806ad8980863fda39e6aead0
```
*
*
* Upgrade cozy-client
```
> chore: Upgrade cozy-client

- package.json
- src/app/domain/authorization/services/SecurityService.ts
- src/app/domain/performances/sendPerformancesByEmail.ts
- src/pouchdb/getLinks.ts
- src/pouchdb/sendDbByEmail.ts
- yarn.lock
```
* Increase replication debounce
* Do not replicate huge io.cozy.jobs database
* Add deviceName in performances export
* Avoid warning related to cozy-client logging
* Upgrade cozy-client
```
> Offline fixes and improvements

- src/screens/login/components/TwakeCustomServerView.tsx
This improve UX for the keyboard
> fix: Set correct input mode for "custom server" field
