src/libs/intents/localMethods.ts

Based on TS typing, a method's `.caller` cannot be `undefined`
But in practice we encountered some crashes when trying to open cozy apps due to undefined `.caller` (it happens only in dev mode)
So we want to use an optional chaining operator here
Note that this operator was present before, but it has been removed in e6ecf3f2d11594d9cfb044e440b3d05aa81830f3 after the file was migrated to TS, probably due to the linter. So we want to add an `eslint-disable` instruction to prevent rolling back this fix

fix: Prevent app crash when `setFlagshipUI.caller` is `undefined`

---

ios/CozyReactNative.xcodeproj/project.pbxproj

When doing a fresh build from scratch, the app would crash on startup with the following error
`Library not loaded: @rpath/hermes.framework/hermes`
To fix this we need to add Hermes to project's linked libraries
More info: https://github.com/facebook/react-native/issues/34601#issuecomment-1239398489

fix: Add Hermes to iOS linked libraries

---

src/libs/intents/setBiometryState.ts

Previously it was also linked on biometry deactivation which we do not want

fix: Link autolock and biometry only on activation

---

src/App.js
src/config/dev.ts
src/libs/services/NetService.js

Strangely enough, the error page used `options` instead of `initialParams` to set the error type. So in some cases there was nothing to display because we didn't have any params even if the ErrorScreen was asked.

fix: Get initial offline route correctly

---

src/locales/fr-FR/translation.json
src/screens/lock/LockScreen.tsx
src/screens/lock/LockScreenTypes.ts
src/screens/lock/hooks/useLockScreen.ts
src/ui/Button/index.tsx
src/ui/Button/styles.ts
src/ui/CozyDialogs/ConfirmDialog.tsx
src/ui/CozyDialogs/styles.ts
src/ui/Icons/Cross.tsx
src/ui/Typography/index.tsx
src/ui/Typography/styles.ts

When the user clicks on the logout button when on unlock screen, ask him to confirm the action.
Leveraging the <Modal> RN component to display a simple modal. Using the cozy-ui ConfirmationDialog API and cozy-ui/figma style variables. There is an issue with the android navigation bar though which stays black when a <Modal> component is rendered
Starting to have magic numbers in stylesheets (even if they all come from Figma)

feat: add confirmation dialog when login out from lock screen

---

README.md

This adds a troubleshooting section for `PhaseScriptExecution failed` error
I encountered this error after a fresh macos install after installing nvm

docs: Add `PhaseScriptExecution failed` error in troubleshooting section

---

src/libs/services/NetService.ts

In #468 we fixed logout method to correctly logs out cozy-client
This state change should be detected by NetService so it can reconfigure itself to ping the Cloudery instead of the previous cozy-stack
> **Note**
> This PR can be merged before #468 , it will just do nothing until this other PR is merged

fix: Reconfigure NetService after logout

---

src/libs/intents/localMethods.ts

This happens on cozy-banks, probably linked to bad cozy-ui/cozy-intent versions
Simple fix native side is to ignore caller name if we don't have access to it

fix: catch error in getting caller name

---

src/libs/intents/setBiometryState.spec.ts
src/libs/intents/setBiometryState.ts
src/libs/intents/toggleSetting.spec.ts
src/libs/intents/toggleSetting.ts

Autolock should always get stored as true if pinCode/biometry are also
set to true.

fix: improve autolock pairing with biometry/pinCode

---

CHANGELOG.md
android/app/build.gradle
ios/CozyReactNative/Info.plist
ios/Podfile.lock
package.json

This PR
- updates the App version to 0.0.31
- creates a new entry for next 0.0.32 release in the CHANGELOG

feat: Bump app version to 0.0.31

---

src/libs/intents/localMethods.ts

This fixes a regression. A previous commit removed the client injection
into the logout intent, so the functionality was disabled.
We correct that mistake by adding the client in asyncLogout call

fix: inject client in asyncLogout

---

CHANGELOG.md
android/app/build.gradle
ios/CozyReactNative.xcodeproj/project.pbxproj
ios/CozyReactNative/Info.plist
package.json

This PR
- updates the App version to 0.0.32
- creates a new entry for next 0.0.33 release in the CHANGELOG

feat: Bump app version to 0.0.32

---

CHANGELOG.md
android/app/build.gradle
ios/CozyReactNative/Info.plist
package.json

This PR
- updates the App version to 0.0.33
- creates a new entry for next 0.0.34 release in the CHANGELOG

feat: Bump app version to 0.0.33

---

CHANGELOG.md
android/app/build.gradle
ios/CozyReactNative/Info.plist
package.json

This PR
- updates the App version to 1.0.0
- creates a new entry for next 1.0.1 release in the CHANGELOG
> **Warning**
> With this PR we updates the buildversion generation rules, now its must be in the form XXYYZZA where XX is the major, YY the minor, ZZ the patch and A the build number

feat: Bump app version to 1.0.0

---

ios/Podfile.lock
package.json
patches/react-native-file-viewer+2.1.5.patch
src/screens/lock/LockScreen.tsx
yarn.lock

On iOS when the users opens a file (PDF, Image, etc), then a QuickLook
controller is displayed on top of the app with the file content
This conflicts with the Lock feature that should show the Lock UI on
top of everything
With current implementation, the QuickLook controller would still be
displayed on top of the Lock screen (this happens if the users send the
apps into the background while viewing a file)
By wrapping the Lock screen into a `FullWindowOverlay` we ensure that
it will be displayed on top of every other elements

fix: Force LockScreen to be on top of the UI

---

src/libs/functions/filePreviewHelper.spec.ts
src/libs/functions/filePreviewHelper.tsx

With previous implementation we created a local file extracted from the raw URL
If the file's name contains spaces, then those will be in the `%20` form (as for any other special characters)
The result is an encoded file name visible in the file-viewer
To prevent this we apply `decodeURI` on the file name
___

fix: Correctly display file name in file-viewer

---

src/libs/functions/openForgotPasswordLink.ts

When clicking the "I forgot my password" button from the Login screen or from the Lock screen, we redirect the user to a cozy-stack page using the OS web browser
By default this page displays a Back button that is intended to be used on a Web only scenario
On mobile we have choice between the Android's native Back button or the iOS "back to app" interaction on the browser's top left, so we don't need the cozy-stack provided button
Since cozy/cozy-stack#3590 we can now request this page to hide the Back button, which is done by this commit
Related PR: cozy/cozy-stack#3590

fix: Do not display the "in page" Back button on password reset page

---

jest.config.js
src/libs/services/NetService.spec.ts
src/libs/services/NetService.ts
src/screens/cozy-app/CozyAppScreen.js
src/screens/error/ErrorScreen.tsx
src/screens/login/LoginScreen.js
src/screens/login/components/ClouderyCreateInstanceView.js
src/screens/login/components/ClouderyView.js

The callbackRoute is mandatory. There is no guard if it's not provided.
handleOffline calls must respect the TS signature

feat: handleOffline() now explicitely includes a callbackRoute 

---

patches/@fengweichong+react-native-gzip+2.0.0.patch

Sentry reported a bug caused by `react-native-gzip`,
created by `commons-io@2.6`.
We decide to patch the library with `patch-package`
to use a commons-io version
compatible with Android 7+
The application was tested on AVD with v7.1 and was not able to reproduce the error

fix: downgrade commons-io in gzip lib to support Android 7+

---

src/ui/TextField/index.tsx

The `cursorColor` prop only works on Android so we want to use `selectionColor` on iOS instead
The drawback of `selectionColor` is that the caret AND the selection highlight are impacted. This is not a problem on iOS as an opacity is applied on the highlight color. However on Android we get white text on white highlight, which is not usable. So we want to apply `selectionColor` only on iOS
More info:
- https://reactnative.dev/docs/textinput#cursorcolor-android
- https://reactnative.dev/docs/textinput#selectioncolor
> **Note**
> We may want to use Secondary color on Android for the selection color. This is what we do in CozyPass Mobile (cf cozy/cozy-pass-mobile@d9b7dbc145ab0622ccc4bc357c228cd4758ad2fb). But the react-native API only changes the highlight color and not the selection handle. …

fix: Set correct caret color on LockScreen on iOS

---

src/components/ConditionalWrapper.tsx
src/components/CondtionalWrapper.spec.tsx
src/screens/lock/LockScreen.tsx

In #501 we added `FullWindowOverlay` to enforce LockScreen on top of UI
If this would work on Android with no functional impact, a warning is displayed on the react-native console saying that `FullWindowOverlay` should not be used on Android (it has no impact)
So this commit add a condition to use it only on iOS
Note: `ConditionalWrapper` component is a copy from cozy/cozy-home@43b7661484b032166823b0489b1a77c39829ae92

fix: Use `FullWindowOverlay` only on iOS

---

package.json
yarn.lock

This reverts commit 81995dc7bfd8023a3fc3c538591eccdb5c02614d
Since previous upgrade flipper does not work anymore on iOS as `pod install` command would remove all reference to the native module
This commit downgrades flipper until the issue is fixed
Related issue: facebook/flipper#4402

fix: Revert react-native-flipper from 0.176.1 to 0.146.1

---

ios/Podfile.lock
package.json
src/components/makeErrorPage.js
src/components/makeHTML.js
src/components/webviews/jsInteractions/jsCozyInjection.js
src/libs/dimensions.ts
src/libs/httpserver/server-helpers.spec.ts
src/libs/httpserver/server-helpers.ts
src/screens/connectors/LauncherView.js
src/screens/cozy-app/CozyAppScreen.Animation.js
src/screens/cozy-app/CozyAppScreen.js
src/screens/lock/view/LockScreenBars.tsx
src/screens/login/CreateInstanceScreen.js
src/screens/login/LoginScreen.js
src/screens/login/OnboardingScreen.js
src/screens/login/components/transitions/TransitionToPasswordView.js
src/screens/welcome/WelcomeScreen.jsx
src/ui/Container/index.tsx
src/ui/Container/styles.ts
yarn.lock

In previous implementation we used `react-native-status-bar-height` and `react-native-android-navbar-height` to compute safe areas for cozy-apps and immersive home
Those libraries did not behave correctly on iPhone 14 Pro and the new `Dynamic Island`
As this is not the first time that those libraries don't give the correct bar sizes, we want to replace them with `react-native-safe-area-context`
This commit does the conversion but also tries to homogenise the `dimensions` API
Note: this library already handles device's ratio so we don't have to convert the navbarHeight anymore

feat: Use react-native-safe-area-context to compute bar dimensions

---

connectors/template/manifest.konnector

Or else, the pilot webview will be init on http://books.toscrape.com and
will fail to fetch https files.

fix: Template connector manifest url to https

---

.gitignore
README.md

This PR updates doc and `.gitignore` file to reflect the new folder structure
Related commit: e749b85272a00e4743dc1880f0b3ff1488c0dc67
BREAKING CHANGE: `api-keys.json` should now be placed in `src/constants/` folder. See README.md file for more info
> **Note**
> I didn't removed the old `src/api-keys.json` to prevent unexpected commit of the old file.

fix: Update doc and `.gitignore` to reflect the move of `api-keys.json`

---

CHANGELOG.md
android/app/build.gradle
ios/CozyReactNative/Info.plist
ios/Podfile.lock
package.json

This PR
- updates the App version to 1.0.1
- creates a new entry for next 1.0.2 release in the CHANGELOG

feat: Bump app version to 1.0.1

---

.env.example
.gitignore
README.md
__tests__/jestSetupFile.js
src/constants/api-keys.ts
src/libs/client.js

This will be how we manage build variables now.
Rationalization of the app secrets and structure that match Github secrets. This change was kindled by the implementation of the CI/CD process.
When developing locally, you definitely don't need all the variables.
Only the auth token for Sentry is mandatory.
You will need more credentials if you need
to produce actual builds locally.
Tested locally and in CI/CD environments.
- Write your Sentry auth key in local .env (SENTRY_AUTH_TOKEN)
- (optional) Write your Safetynet key in local .env (ANDROID_SAFETY_NET_API_KEY)

feat: add .env file

---

src/hooks/useLauncherClient.ts
src/libs/Launcher.js
src/libs/client.js
src/libs/connectors/getLauncherClient.ts
src/libs/connectors/models.ts
src/libs/cozyAppBundle/cozyAppBundle.functions.ts
src/libs/cozyAppBundle/cozyAppBundle.ts
src/screens/connectors/LauncherView.js
src/screens/home/HomeScreen.tsx

- Handle stack-only connectors (no registry publication)
- Provide the correct clients to both Launcher and LauncherView
- Read main.js instead of index.js in the cache
Connectors weren't launching properly, especially if not published in the registry
- Everyone working on connectors should perceive better workflow and less bugs
- Manually, installing `git://github.com/konnectors/template_ccc.git#build` on my staging environment (not local dev stack)

fix: update connector launcher

---

android/app/build.gradle

This fix comes from https://github.com/facebook/react-native/issues/35979

fix: duplicate versions of jetified-kotlin-stdlib-1 when building android version

---

src/screens/home/HomeScreen.tsx

'CozyProvider' is defined but never used
Will fix the only quality_checks warning

fix: remove warning from CI check

---

package.json
src/libs/Launcher.js
src/libs/connectorLibs/saveFiles.js
yarn.lock

This PR should remove all 6 calls to cozy-client-js in the saveFiles.js file.

feat: Remove cozy-client-js from saveFiles

---

src/core/tools/interpolate.ts
src/libs/connectors/models.ts
src/locales/fr-FR/translation.json
src/screens/home/HomeScreen.tsx
src/screens/home/components/ErrorParallelConnectors.tsx
src/screens/home/components/HomeView.js
src/screens/home/hooks/useLauncherClient.ts
src/screens/home/hooks/useLauncherContext.tsx
src/screens/home/hooks/useLauncherWrapper.ts
src/ui/CozyDialogs/ConfirmDialog.tsx

- Forbid the launch of a new connector if one is already running
- Display a dialog with confirm so the user can understand what happened
- This is needed because connectors can't run correctly in parallel at the moment so we have to avoid this situation in the first place
- For the moment it should reduce the number of bugs for local development. Although if a connector never stops, you can never open another one so it can be a big problem. But it's easy to hack the feature to disable it.
- Test manually only. I wanted to add integration tests but it's too complex at the moment with the current architecture. I will work on having a LauncherView mock that can be useful and usable for more testing

Feat  forbid parallel connectors   rework

---

ios/CozyReactNative.xcodeproj/project.pbxproj

In 9be69c37904773d2291f4620245f78d36b75554b we added Hermes to iOS linked libraries to prevent an app crash on startup
As today we start having more developers working on the iOS environment we realised that the previous bug was environment specific and if we build the project from a clean environment then the app runs correctly without the previous fix
Worst, the previous fix makes their build fail
So we chose to revert the fix and also remove all Hermes reference from the `project.pbxproj` file
This choice has been made after we compared the `pbxproj` file with the one from a newly created react-native 0.66.4 project with Hermes enabled and found that it contains no Hermes reference.

fix: Remove Hermes from iOS linked libraries

---

src/libs/connectors/cleanConnectorsOnBoot.ts
src/redux/ConnectorState/CurrentConnectorSlice.ts

- Delete the running connector when we boot the app after recovery
- We need a clean state when app starts and recovered logs. No connector should be running at this point.
- This impact all features that rely on the currentConnector state. Overall, it solidifies the feature.
- Manual test as it's fairly straightforward

feat: setConnector to undefined on boot

---

src/App.js
src/hooks/useAppBootstrap.functions.ts
src/hooks/useAppBootstrap.js
src/hooks/useAppBootstrap.spec.js
src/libs/functions/openApp.js
src/libs/intents/localMethods.spec.ts
src/libs/intents/localMethods.ts
src/screens/home/components/HomeView.js

With previous implementation we had to use `setInitialRoute()` and `setInitialScreen()` to define the initial app state
This was problematic as it was difficult to understand which route should be defined as `initial route` and which one should be defined as `initial screen`
Also the usage of `initialRoute.stack = <some_route>` and `initialScreen.stack = <some_route>` with addition to the presence of `intialRoute.route = routes.stack` made it even more confusing about what is a `root` and what is a `stack`
This complexity was due to the fact that we split the routes declarations between `RootNavigator` and `StackNavigator`. Here again the rule defining where to put each route was unclear
To simplify this we chose to refactor the code to use one single `Navigator` for every routes
This …

fix: Rework `useAppBootsrap` and fix deeplinks implementations

---

connectors/connectorLibs/ContentScript.js
src/@types/cozy-client.d.ts
src/hooks/useConnectors.ts
src/libs/ReactNativeLauncher.js
src/libs/connectors/cleanConnectorsOnBoot.ts
src/libs/connectors/sendConnectorsLogs.spec.js
src/libs/connectors/sendConnectorsLogs.ts
src/redux/ConnectorState/ConnectorLogsSlice.ts
src/screens/connectors/LauncherView.js
src/screens/home/HomeScreen.tsx
src/screens/home/hooks/useLauncherContext.tsx

This PR send konnectors logs in batch to the stack.
They respect the format of stack.
They are filtered on possible level (or debug is the default level) : debug, info, warn, error
They are log into the flagship app too corresponding to their level.

feat: Sending konnectors logs to stack in batch

---

.github/workflows/build-android-prod.yml

This PR fixes the Android deploy workflow by setting correct package name and targeted track
It also remove unused props and edit the workflow's name as it should be unique for better readability in the Github Actions page
Finally, until we validate the CI behaviour we want this workflow to be manually triggered instead of being paired with a Github release

fix: Set correct project info for Android deploy workflow and trigger it on dispatch

---

src/screens/connectors/LauncherView.js

- Add "UNKNOWN_ERROR" if LauncherView crashes on init
- Add "VENDOR_ERROR" if LauncherView crashes because of a WebView error (browser-like error, like error_disconnected, not http request errors)
- The goal is to send more information to the stack when something goes wrong
- It should impact people trying to debug connectors. It has no impact on the implementation of the connectors.
- Please note I could NOT add an online check before the user launches the connector, because it is handled Harvest side before being redirected to the Native side. So whatever I do, I will always be too late when doing an online check at connector start, unless I do it way too early on harvest open.
- Tested manually, but didn't test on the stack end to check the received result

feat: add more context to connectors errors

---

.github/workflows/build-ios-dev.yml
.github/workflows/build-ios-prod.yml
ios/CozyReactNative.xcodeproj/project.pbxproj
ios/Podfile
ios/sentry.properties
ios/sentry.properties.example

- Add a GitHub Workflow that can be triggered manually on the master branch
- Build iOS application `.ipa` file
- Upload this file in the workflow `.zip` artefact
- Add a GitHub Workflow that can be triggered manually on the master branch
- Build iOS application `.ipa` file
- Upload this file in TestFlight with Github Secrets
This is a step in the more overarching CI/CD feature of the application.
It should impact people wanting to create a development build, it will be easy as a click and not require any technical knowledge.
It should also ease the deployment process.
- Tested build locally with provided secrets
- Tested build on GitHub on push (deactivated for merging)
- Did **NOT** test deployment to Testflight

feat: add iOS CI

---

src/libs/functions/convertMinutesToMs.ts
src/screens/connectors/LauncherView.js
src/screens/connectors/constants/connectors-constants.ts
src/screens/connectors/core/handleTimeout.spec.ts
src/screens/connectors/core/handleTimeout.ts

- When LauncherView is instantiated, it starts a 15 minutes timer. It will kill itself after this time has passed if it didn't stop the timer beforehand.
- We're doing this to cleanup broken states in connectors
- People working on connectors might experience less bugs
- Unit test for the timeout function
- Manually for the actual integration test

feat: add connector timeout

---

src/libs/functions/iconTable.spec.ts
src/libs/functions/iconTable.ts

`attemptFetchApps` used directly `fetchJSON` bypassing cozy-client cache. Now we use `fetchQueryAndGetFromState` which uses cozy-client cache.

feat: Use cache for fetch apps query

---

src/libs/functions/passwordHelpers.js

PBKDF2 default iteration number has been increased on cozy-stack so we want to replicate this new value on Flagship onboarding scenario
The login scenario is already querying the cozy-stack iteration number from `/public/prelogin` route, so it is not impacted
The onboarding scenario cannot query this value has the `/public/prelogin` route would return `KdfIterations:0` until the onboarding completes, so instead we use the default iteration number that is hard coded into the app's code
Related PR: cozy/cozy-stack#3604

fix: Increase default PBKDF2 iteration number to from 100000 to 650000

---

package.json
yarn.lock

This PR upgrade cozy-clisk to fix the date verification in connectors.
Has been tested successfully with Alan.

fix: Upgrade cozy-clisk to fix date verification

---

.github/workflows/build-android-dev.yml
.github/workflows/build-android-prod.yml
CHANGELOG.md
android/app/build.gradle
android/app/proguard-rules.pro
ios/CozyReactNative/Info.plist
package.json

This PR
- updates the App version to 1.0.3
- creates a new entry for next 1.0.4 release in the CHANGELOG
This PR also fixes the CI process by:
- Enforcing Node 16
- Fixing Proguard configuration with react-native-config
- Fixing workflow files

feat: Bump app version to 1.0.1 and fix CI

---

src/constants/strings.json
src/libs/functions/openApp.js
src/libs/functions/openApp.spec.js
src/libs/functions/session.js
src/libs/functions/urlHelpers.js
src/libs/functions/urlHelpers.spec.js

- This will check when opening an URL if it's from the same nested cozy
- Previously we determined that a nested cozy could never navigate to itself
- It impacts everyone with a nested cozy, so mainly dev environments
- Manually, no unit tests as of now. The shape of deconstructed cozy web link is strange in nested mode though, I'm not sure if it's returning correct data

fix: handle nested domains for `isSameCozy`

---

src/App.js
src/constants/routes.js
src/libs/functions/openApp.js

Previously this function opened the URL "home". But this route is a Navigator route and the slug param was lost.
By navigating to "default" instead (which is the actual home route), we correctly keep the slug param and the connector opens.
The HomeView did not receive any param after a navigation so we could not open a Konnector from the cozy-store

fix: update openConnectorInHome

---

package.json
yarn.lock

```
anc@desktop:~/cozy/cozy-react-native$ yarn why cozy-ui
yarn why v1.22.19
[1/4] Why do we have the module "cozy-ui"...?
[2/4] Initialising dependency graph...
warning Resolution field "@typescript-eslint/eslint-plugin@5.36.0" is incompatible with requested version "@typescript-eslint/eslint-plugin@^4.5.0"
warning Resolution field "@typescript-eslint/eslint-plugin@5.36.0" is incompatible with requested version "@typescript-eslint/eslint-plugin@5.44.0"
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "cozy-ui@52.0.1"
info Has been hoisted to "cozy-ui"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "16.66MB"
info Disk size with unique dependencies: "58.1MB"
info Disk size with transitive dependencies: "98.38MB" …
```

chore: remove cozy-ui

---

src/@types/cozy-clisk.d.ts
src/libs/Launcher.js
src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js
src/screens/connectors/LauncherView.js
src/screens/home/hooks/useLauncherClient.ts

Now, the Launcher creates the account and trigger, not harvest.
The trigger is also launched.
This allows for faster account and trigger creation since the flagship
app will only have to check clisk specific aspects.
At the moment, account and trigger are still created even if the login fails.
What is missing is a way to display an error in the amiral application or harvest without a job
And we need to have a job result to trace connections attempts which have failed in logs
- feat: Use connector slug in launcher
- feat: Upgrade cozy-client to v35
- feat: Ensure account and trigger on flagship app side
- docs: Add @ts-check

feat: Ensure account and trigger on the flagship app side

---

src/libs/Launcher.js
src/libs/ReactNativeLauncher.js
src/screens/home/components/HomeView.js
src/screens/konnectors/LauncherView.js

When the launcher needs to create an account and trigger, it will
redirect the home application to the harvest route related to the
created account.
This will allow the user to see the execution of his konnector

feat: Redirect to created account after creation

---

android/app/src/main/AndroidManifest.xml
docs/how-to-debug-onboarding-partner.md
package.json
src/constants/dev-config.ts
src/constants/strings.json
src/core/tools/dev.ts
src/core/tools/env.ts
src/screens/welcome/WelcomeScreen.jsx
src/screens/welcome/install-referrer/androidPlayInstallReferrer.ts
src/screens/welcome/install-referrer/onboardingPartner.spec.js
src/screens/welcome/install-referrer/onboardingPartner.ts
src/screens/welcome/install-referrer/useInstallReferrer.ts
yarn.lock

On App's first launch, we want to detect the installation context so we
can extract Onboarding Partner and display custom instructions to our
users
To do this we use Google Play Install Referrer API, and so it is
enabled only on Android phones
This PR only displays the raw OnboardingPartner info (if found)
Real screen implementation will be done later

feat: Display custom WelcomeScreen when OnboardingPartner context found

---

scripts/reset-android.sh

This will erase everything gradle/npm/yarn,
and reinstall node modules.
But not gradle files.
You have to chmod +x the file before using it

feat: add shell script to reset Android env

---

src/libs/cozyAppBundle/cozyAppBundle.functions.spec.ts
src/libs/cozyAppBundle/cozyAppBundle.functions.ts

On #525 we added bundle cleanup feature to remove all previous bundle
versions
This introduced a bug as the initial bundle is stored in "embedded"
folder which is not named after the version (i.e 1.50.0)
To prevent this, chose to never delete the "embedded" folder.

fix: Keep embedded folder on cozyAppBundle update

---

patches/react-native-fs+2.20.0.patch

This patch will handle 303 response on download when using the local stack with a http url and not https.
An issue has been created on the react-native-fs : https://github.com/itinance/react-native-fs/pull/1153

feat: Patch rnfs to handle 303 http code on download

---

src/@types/cozy-client.d.ts
src/hooks/useAppBootstrap.functions.ts
src/hooks/useAppBootstrap.js
src/libs/functions/formatOnboardingRedirection.spec.ts
src/libs/functions/formatOnboardingRedirection.ts

**End goal** : be able to open a specific app at the end of the onboarding.
The way to get the _onboarded_redirection_ is not sure for the moment. So it is a first possibility based on the onboarding email, which will be useful for testing purpose anyway.
**About the code**
~~I am not very happy about the result especially because I added code in a lot of different places. Feel free to challenge it. What do you think about the onboardingRedirection state used to pass the redirection between onboarding and the useAppBoostrap hook for example?~~
**How to test**
- Encode your onboarded_redirection param like _drive/#/_ (root of Cozy Drive app) => _drive%2F%23%2F_
- Encode your email in the onboard_url param like _oib35043@zslsz.com_ => _oib35043%40zslsz.com_
- Forge the link and open it with …

Open app at onboarding end with email link

---

.github/workflows/build-android-dev.yml
CHANGELOG.md
android/app/build.gradle
ios/CozyReactNative/Info.plist
package.json

This PR
- updates the App version to 1.0.4
- creates a new entry for next 1.0.5 release in the CHANGELOG

feat: Bump app version to 1.0.4

---

scripts/install-home-registry.cmd.ts

Update ios home dir
It used the 'iOS' dir, but the correct casing is 'ios'.
It seems it still worked for some reason, but it's best to be safe
ci/dev

fix: update install home script

---

src/libs/cozyAppBundle/cozyAppBundle.ts

In `updateCozyAppBundle`, `setCurrentAppVersionForFqdnAndSlug` is responsible for storing the newly downloaded cozy-app's version into the device's asyncStorage
In the first implementation of `updateCozyAppBundle`, we didn't await for `setCurrentAppVersionForFqdnAndSlug` to be executed as it was the method's last instruction and because we didn't need to read the value from asyncStorage until the next app's cold start. This method was used to handle cozy-apps only
In #525 we started using this method for Client Side Connectors and we needed to read the new value from asyncStorage just after the `updateCozyAppBundle` call
The side effect is that `setCurrentAppVersionForFqdnAndSlug` is in a race condition with `ReactNativeLauncher.getKonnectorBundle()` call that happens just after
So we now …

fix: Await for setCurrentAppVersionForFqdnAndSlug in updateCozyAppBundle

---

src/screens/konnectors/LauncherView.js

Just display an empty view instead.
The "loading" text was clashing with the backdrop overlay and created a visual artifact.
You can see the bug it created on the following image:

feat: remove placeholder text

---

src/libs/intents/setFlagshipUI.ts

shouldRepaintStatusBar() had a bug where it would detect false positives and repaint when it should not

fix: handle shouldRepaintStatusBar better

---

src/libs/functions/openApp.js

- openApp doesn't have href parameter when opening a konnector
- thus it will always fail the shouldOpenInIAB check
- manage it before the check

fix: openApp should let Konnectors go through

---

src/hooks/useKonnectors.ts
src/libs/Launcher.js
src/libs/ReactNativeLauncher.js
src/libs/konnectors/cleanKonnectorsOnBoot.ts
src/libs/konnectors/stopKonnectorJob.ts
src/redux/KonnectorState/CurrentKonnectorSlice.ts
src/screens/home/HomeScreen.tsx
src/screens/home/hooks/useLauncherContext.tsx
src/screens/konnectors/LauncherView.js

The current job id is saves in the redux store when the job is stated by the flagship app and removed on the end of the clisk konnector execution.
If the job id is still in redux store when reloading the flagship app, it means that the flagship app failed while running the clisk konnector job. The flagship app then mark the current job as "context deadline exceeded" which is the error code for timeout job error on cozy stack.

feat: Force stop the current job id if any on flagship app start

---

src/libs/Launcher.js
src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js
src/screens/konnectors/constants/konnectors-constants.ts

This trigger is created when a clisk konnector is created and is
scheduled to run the cliskTimeout service 20min after the creation
of the job and will force the termination of the job
This trigger will be automatically removed when the job is stopped by
the flagship application
Depends on https://github.com/cozy/cozy-home/pull/1897 to be deployed on home application

feat: Create a clisk timeout trigger

---

src/App.js
src/constants/strings.json
src/hooks/useCozyEnvironmentOverride.functions.ts
src/hooks/useCozyEnvironmentOverride.spec.ts
src/hooks/useCozyEnvironmentOverride.ts
src/screens/login/cloudery-env/clouderyEnv.spec.ts
src/screens/login/cloudery-env/clouderyEnv.ts
src/screens/login/cloudery-env/useClouderyUrl.ts
src/screens/login/components/ClouderyView.js
src/screens/login/components/ClouderyView.spec.js
src/screens/welcome/install-referrer/onboardingPartner.ts

We want to be able to override OnboardingPartner and ClouderyEnv by using an universal link or a scheme link
ClouderyEnv is a new configuration that allow to define if the ClouderyView should display the production, integration or development cloudery
The app should be able to intercept links containing `cozy_env_override` keyword and extract new OnboardingParner and
ClouderyEnv configuration from it
This feature is needed for debugging purpose so we display a react-native alert when a link is intercepted and the configuration is overriden
___
TODO:

feat: Implement OnboardingPartner and ClouderyEnv override using links

---

src/libs/konnectors/stopKonnectorJob.ts

We changed the cliskTimeout Trigger to @in trigger. This is now
reflected when we remove the trigger when the job is stopped (to avoid
to run a service to stop a job which is already stopped)

fix: Remove @in cliskTimeoutTrigger instead of @at

---

src/App.js
src/screens/cozy-app/CozyAppScreen.js
src/screens/home/HomeStateProvider.js
src/screens/home/components/HomeView.js

When opening the app from a deep link that target a CozyApp, the current implementation start loading the HomeView and the CozyAppScreen simultaneously
This is not optimal as we want to display CozyAppScreen as fast as possible. The HomeView only needs to be loaded when the user clicks on the Home button or the Back button
So we want to start loading the HomeView only after the CozyAppScreen finished loading

feat: Wait for CozyApp to be loaded before loading HomeView if DeepLink

---

src/libs/Launcher.js
src/libs/Launcher.spec.js

With @Ldoppea , we find a bug with the recent update regarding the account creation.
In this PR we fix it by giving the rest of the context in addition to the destructurate variables from the startContext.
We spot that an account is needed to save the user's credentials, so it add a little condition returning null if no accounts are present in the startContext at the time getCredentials is called.

Context for ccc

---

src/constants/strings.json
src/screens/login/cloudery-env/clouderyEnv.spec.ts
src/screens/login/cloudery-env/clouderyEnv.ts
src/screens/welcome/WelcomeScreen.jsx

> **Warning**
> This PR relies on cozy-stack new routes that are not implemented yet 
When the App detect OnboardingPartner context, it should skip the WelcomeScreen and directly display the ClouderyView instead
Also it should pass OnboardingPartner context to the Cloudery view so it can adapt its content to the detected partner
___
- #632
- This PR reverts the WelcomeScreen custom page as we now want to skip this step instead (it will be handled by the Cloudery when partner is set)

feat: Pass OnboardingPartner context to ClouderyView when exist

---

src/libs/ReactNativeLauncher.js
src/screens/home/components/HomeView.js

When the user has run a clisk konnector, harvest display a "running"
state. If the user aborts the execution of the clisk konnector (login
failed for example), we want harvest to go back to idle state.
A signal is sent to harvest via postMessage to allow harvest to go to
the proper state.
Harvest side : https://github.com/cozy/cozy-libs/pull/2056

feat: Send a signal to harvest to release the execution state

---

CHANGELOG.md
android/app/build.gradle
ios/CozyReactNative/Info.plist
package.json

This PR
- updates the App version to 1.0.6
- creates a new entry for next 1.0.7 release in the CHANGELOG

feat: Bump app version to 1.0.6

---

src/components/webviews/ReloadInterceptorWebView.js

We can display a Drive Intent from Cozy-Banks
by clicking on the chip associated to the transactions.
This Drive intent shows the Viewer and this viewer has a "Download" button. This button was not working because for iOS we have to make some work in order to be download files, but we only did it for the
main frame. And since Intents are not in the main
frame, it was not working for them.
I fixed this issue by checking the link for every frames.

fix(iOS): Download file from Intent

---

src/screens/konnectors/LauncherView.js

onWorkerError can be called when the the webview fails to load.
I could not reproduce it but it happens.
Now, with the proper binding, the job will be properly stopped on this error

fix: Bind onWorkerError to launcherView

---

src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js

Now when an error occurs in the worker, launcher will throw it back to
the pilot to have the konnector execution stopped without any unhandled
rejected promise

fix: Let worker error throw back to the pilot

---

CHANGELOG.md
android/app/build.gradle
ios/CozyReactNative/Info.plist
package.json

This PR
- updates the App version to 1.0.7
- creates a new entry for next 1.0.8 release in the CHANGELOG

feat: Bump app version to 1.0.7

---

src/screens/konnectors/LauncherView.js

Now the initialization of clisk view is done in the same method as
installation of the konnector.
Any error inside this method is intercepted, logged in the konnector
logs and passed the start method as UNKNOWN_ERROR
This way, it will be possible to get this error logged in production

feat: Intercept handshake failed errors from clisk webviews

---

src/libs/cozyAppBundle/cozyAppBundle.ts

When working on a local simulator, it's useful to have this log in order to be able to manualy add a few logs inside the bundle without the need to have a watch or else on konnectors / apps.

feat: Add log for DestinationPath

---

src/libs/defaultRedirection/defaultRedirection.ts

Since requesting just the end of the id is deprecated (since the latest upgrade of cozy-client), let's adapt the code to request the real id.

fix: Query warning

---

android/app/src/main/AndroidManifest.xml

UL was not working because I forgot to add the
android:autoVerify="true" tag for the intent...
Adding it, makes the UL work.
I also converted the old definition to the new one, see https://stackoverflow.com/questions/68144323/app-links-legacy-failure-verification-error-on-android-12 for more information.
UL tested:
```
adb shell am start -W -a android.intent.action.VIEW -d "https://links.mycozy.cloud/flagship/\?fallback\=https%3A%2F%2Ffoo-home.mycozy.cloud%2F%23%2Fconnected%2Falan%2Faccounts%2F123456789\#/connected/alan/accounts/123456789"
```

fix: Android Universal Link

---

src/screens/konnectors/LauncherView.js

- When connecting a Konnector account, onCreatedAccount() will use the setParams() API instead of the navigate() API (react-navigation). This makes it possible to navigate to the Harvest logged in view while connecting for the first time.
- Navigating to 'default' or to 'home' could not work correctly as it was already the current page. It had unexpected behaviours and resulted in various cryptic navigation state update bugs. By using setParams() we are modifying the current route, and therefore homeview behaves correctly and gives the correct uri to cozy-home and harvest.
- When connecting an account to a CCC
- Only test manually and on local environment. Unit testing would be very hard at this point in time (but needed) and integration close to impossible

fix: use setParams instead of navigate in LauncherView

---

src/libs/Launcher.functions.spec.ts
src/libs/Launcher.functions.ts
src/libs/Launcher.js

- When connecting a Konnector account, we check if any account is linked to this connector. If this is the case, we delete all of them. This avoids multi-account on a CCC.
- For now, we don't want CCC to use the multiple account feature.
- Every CCC
- Tested manually with accounts created in local CouchDB
- Added unit test for the new function
- The new function logs what it does for debugging purposes

feat: delete existing accounts if needed

---

src/App.js
src/AppRouter.jsx

`MainAppNavigator`, `RootNavigator` and `Nav` were declared inside of `App` and `WrappedApp` functional components
This would produce unintended re-render, or worst, unintended re-mount of the entire router if `App` or `WrappedApp` would have to re-render due to changes on upper context
Extracting those component from `App` and `WrappedApp` would stabilize the component tree
___
This PR is needed for https://github.com/cozy/cozy-flagship-app/pull/700

Refactor: Extract Nav and Router components into their own components

---

package.json
src/libs/Launcher.js
src/libs/Launcher.spec.js
src/libs/ReactNativeLauncher.spec.js
src/libs/client.js
src/libs/client.spec.js
src/libs/konnectors/getLauncherClient.ts
src/libs/konnectors/models.ts
src/screens/home/hooks/useLauncherClient.ts
yarn.lock

The goal is to have an instanciated cozy-client with the right metadata. Before we had the right token, but the appMetadata was not right.
The createdByApp was right for the io.cozy.files since the stack doesn't read the value from the client, but for triggers or bills, the createdByApp was not right.
With this PR, we should have the right metadata now.
CozyClient is also able to take a `sourceAccount` appMetadata, but I think we don't have a `sourceAccount` at the first launch. So we should update it later, but I don't think cozy-client API allow this ATM.
I also added the appMetadata to the flagship client.

fix: Set appMetadata for LauncherClient

---

__tests__/jestSetupFile.js
src/screens/konnectors/LauncherView.js
src/screens/konnectors/core/handleBackPress.spec.ts
src/screens/konnectors/core/handleBackPress.ts

This PR will allow users to backPress from their opened CCC to go back to the previous screen.
It uses the same callback as the "return to my Cozy" button.

feat: handle backpress in idle CCC

---

src/screens/login/components/ClouderyViewSwitch.tsx
src/screens/login/components/OidcOnboardingView.tsx
src/screens/login/components/functions/interceptExternalLinks.ts
src/screens/login/components/functions/oidc.ts

Cloudery can display some external links in partners pages, so we should intercept them and display them in an InAppBrowser
Also some links would be open by the ClouderyView using `window.open()` method. This should be used for the "terms and condition" PDF that is stored on the Cloudery (and so we cannot detect URL.origin change)
By using `onOpenWindow` we would intercept those URLs

fix: Intercept external links in OidcOnboardingView

---

src/screens/login/LoginScreen.js

When receiving fqdn from route parameter, we don't have access to partner context so we enforce default Cozy color as background
We need to enforce it as the app may already be opened to a neutral or partner Cloudery with a different background color

fix: Set Cozy's background color when login from email link

---

src/libs/Launcher.js
src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js
src/screens/home/components/HomeView.js

This depends on https://github.com/cozy/cozy-libs/pull/2091 to be
deployed on home application to work completely

feat: Send LOGIN_SUCCESS event via postMessage to the home application

---

src/screens/login/CreateInstanceScreen.js
src/screens/login/components/ClouderyCreateInstanceView.js

This PR adapt screens colors and external links interception in CreateInstanceScreen. This screen is used in the Onboarding from email scenario. So we apply the same mechanisms that we implemented for the LoginScreen.
> **Note**
> We may want to mutualize the WebView code between ClouderyCreateInstanceView and ClouderyView, but I prefer to wait to have a better idea about what this implies. Also this is not mandatory for the tomorrow's deadline

fix: Handle email onboarding scenario

---

src/App.js

Today implementation doesn't clear the `cozy-client` on logout
On login, the `setClient` will trigger a switch in App.js that recreates the `<Nav />` component inside of `<CozyProvider />`. This re-trigger the `useAppBootstrap` hook and re-compute the `initialRoute` which now outputs the `home` screen (because we now have a logged-in cozy-client)
On logout, we navigate to the `welcome` screen without clearing the client. This does not re-trigger the `useAppBootstrap` hook which stays in the same state. This behaviour is not problematic
But if we login again, then the `useAppBootstrap` hook won't be re-triggered as it is designed to be run only one time (see `initialRoute === 'fetching'` condition). This behaviour is problematic because we are not redirected to the `home` screen anymore …

fix: Clear client on logout

---

src/screens/home/components/HomeView.js

When the user clicks on Home's logout button, the
`localMethods.asyncLogout()` method would logout the cozy-client and navigate to the `welcome` screen
The navigation would trigger the HomeView's blur event and then trigger the `setUri()` which would re-rerender the Home's CozyProxyWebView to load the new `uri`
Side effect is that the `updateCozyAppBundleInBackground()` method would be started and 10s later the bundle update process would start. Which should not happen as we are logged-out
To fix this we want to prevent the `setUri()` call if cozy-client is logged-out

fix: Do not change Home's uri on `blur` event if client is logged-out

---

.github/workflows/quality_checks.yml

~~Current `quality_check` workflow is only triggered on PRs that target the `master` branch~~
~~We want to allow meta PRs to be checked by this workflow too~~
~~To make this happens, we should now name branches `feat/meta_pr_*`~~
Current `quality_check` workflow is only triggered on PRs that target
the `master` branch
We want all PRs to be checked by this workflow too
___
This PR is for https://github.com/cozy/cozy-flagship-app/pull/708 that is the target branch for all OIDC PRs and I noticed that all child PRs were not checked

feat: Trigger quality_checks CI on all PRs

---

src/libs/Launcher.js
src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js
src/screens/home/components/HomeView.js

When no account has been created yet.
This will allow harvest to display a non persistent message to
the user.
In draft waiting for the harvest side PR

feat: Send clisk error message to harvest

---

src/libs/functions/keyboardHelper.ts
src/screens/login/LoginScreen.js
src/screens/login/components/ClouderyCreateInstanceView.js
src/screens/login/components/ClouderyView.js
src/screens/login/components/ClouderyViewSwitch.tsx
src/screens/login/components/OidcOnboardingView.tsx
src/screens/login/components/functions/clouderyBackgroundFetcher.ts
src/screens/welcome/WelcomeScreen.jsx

In previous implementations, we handled field autofocus from the react-native components by predicting which field would be displayed
Those fields were easily predictable as only a few login and onboarding scenario were implemented
Now that we implemented OIDC scenario, it is harder to predict those fields. For example, the link from email onboarding can now redirect to the Cloudery's FQDN choice page, or the ToS page
The new implementation allow to focus whatever DOM field that has `autofocus` prop. If no `autofocus` field is present, then no focus is triggered. This would prevent the keyboard to appear on the ToS page
Also as this mechanism is triggered from the HTML page and on page's load event, then the keyboard focus is handled on every navigation, which would make the autofocus …

feat: Make field autofocus more generic in login and onboarding screens

---

src/screens/login/LoginScreen.js
src/screens/login/components/PasswordView.js
src/screens/login/components/functions/clouderyBackgroundFetcher.ts

**fix: Handle Android's navigation bar color on Cloudery pages**
In previous implementation we only handled Status bar colors on both
Android and iOS
But we forgot to handle navigation bar on Android
This commit add support for the navigation bar
Note that this does not concern the gesture bar on modern android
devices as this bar already adapts its color in a dynamic way
----
**fix: Handle bar colors on PasswordView**
Now that we implemented neutral screens with white background, the
PasswordView should call the `setBackgroundColor` to re-establish the
Cozy blue color

fix: Handle Android's navigation bar color on Cloudery pages and fix bars colour on PasswordView

---

android/app/src/main/res/values/strings.xml
docs/how-to-retrieve-logs-in-release.md
ios/CozyReactNative/Info.plist
ios/CozyReactNativeDev-Info.plist

We want to rename the app to better fit the "neutral" scenario we are implementing
Related PR: #708

feat: Rename app from `Cozy Cloud` to `Cloud Personnel`

---

src/hooks/useAppBootstrap.js
src/screens/login/components/ClouderyCreateInstanceView.js
src/screens/login/components/ClouderyView.js
src/screens/login/components/OidcOnboardingView.tsx

Due to the increasing number of login and onboarding scenario it becomes necessary to add logs on Cloudery views so we can track what state is triggered by useAppBootstrap and which URLs are intercepted by the app (from Cloudery webviews navigation and from universal links)
So this PR add some logs to track those scenario from the react-native console

feat: Add logs for Cloudery views navigations and URL interception

---

src/hooks/useAppBootstrap.functions.ts
src/hooks/useAppBootstrap.js
src/hooks/useAppBootstrap.spec.js
src/libs/client.js
src/libs/functions/getOnboardingDataFromRequest.js
src/libs/functions/getOnboardingDataFromRequest.spec.js
src/screens/login/CreateInstanceScreen.js
src/screens/login/LoginScreen.js
src/screens/login/OnboardingScreen.js
src/screens/login/components/ClouderyCreateInstanceView.js

We want the user to be able to create and login to their Cozy using passwordless authentication
To make this possible, when the user onboard to a partner context by entering their email, then the sent email contains a `magic link` that allows to complete the onboarding without entering any password
Then with this account type, the user can login using the same principle. After entering their email or their instance url, the Cloudery send a `magic link` by email and this magic link would allow to login without the password step
Related PR: cozy/cozy-stack#3872
> **Note**
> This PR adds more complexity to client.js, so I added another PR to refactor it: #734

feat: Add Magic Link support to Login and Onboarding scenario

---

src/libs/clientHelpers/connectClient.ts
src/libs/clientHelpers/magicLink.ts
src/libs/clientHelpers/types.ts
src/locales/fr-FR/translation.json
src/screens/login/LoginScreen.js

On Magic Link scenario, if the user enabled 2FA, then then 2FA should be done using the user's password instead of the usual code sent by email
This choice has been made because the Magic Link scenario already uses the email channel, so a 2FA code sent through the same channel would add no benefits to security. So instead we ask to the user for their password
To make this possible, we will have to modify cozy-settings so the 2FA feature requires a password to be set on the Cozy
> **Note**
> I'm not happy with the complexity I added on the LoginScreen with this PR but also with the OIDC one. We now have a lot of similar methods (`startOAuth`, `continueOAuth`, `startOidcOAuth`, `startMagicLinkOAuth`, `continueMagicLinkOAuth`) but with enough difference to make it difficult to factorize …

feat: Handle password based 2FA on Magic Link login scenario

---

src/screens/login/CreateInstanceScreen.js
src/screens/login/LoginScreen.js
src/screens/login/OnboardingScreen.js
src/screens/login/components/CozyLogoScreen.tsx
src/screens/login/components/OnboardingPasswordView.js
src/screens/login/components/functions/clouderyBackgroundFetcher.ts
src/screens/login/components/transitions/TransitionToAuthorizeView.js

When doing MagicLink onboarding, we need to display a screen during the
HTTP requests processing
We chose to display a Cozy logo with a background based on the context
The context color is now passed as a route parameter from the Instance
creation screen (which did get the background color from the Cloudery
webview)
This new Cozy Logo view is now used as a loading screen on the
OnboardinScreen instead of the `showSplashscreen` that cannot be
customized with the context color
___
This PR also adapt the TransitionToAuthorizeView background on LoginScreen which is the cozy logo animation just before the Authorize screen in IAB
___
> **Warning**
> We still have to adapt the colour of the Splashscreen which seems impossible with the current react-native-bootsplash plugin, so we will have to …

feat: Improve transitions on MagicLink onboarding and on login 2FA

---

ios/CozyReactNativeDev-Info.plist

This pull request adds French localization support to the iOS app by updating the Info.plist file. It includes the 'fr' language in the CFBundleLocalizations key, which informs iOS that our app supports French localization. As a result, system-provided UI components will respect the device's language settings when set to French.
Please note that this change only affects build-time settings and does not allow for changing the app's language at runtime based on user settings. In the future, if we decide to support multiple languages and allow users to change the app's language at runtime, we can consider implementing a localization library such as react-i18next or react-native-localize. This would enable us to manage translations within the React Native code and update the displayed …

fix: Add French localization support in Info.plist

---

android/app/src/main/res/values/strings.xml
docs/how-to-retrieve-logs-in-release.md
ios/CozyReactNative/Info.plist
ios/CozyReactNativeDev-Info.plist

In previous PR we renamed the app to `Cloud Personnel` to better fit the "neutral" scenario we are implementing
But this new name was too long and would be truncated in some OS. For example iOS would truncate any app name between 11 and 13 characters based on the OS' font zoom setting. The Android rule can differ on each model/brand but we should be safe if choosing a name with less than 12 characters (based on unofficial answers on StackOverflow)
So we rename it again but this time we want to use `Cozy` name
Related PR: #735

feat: Rename app from `Cloud Personnel` to `Cozy`

---

src/screens/login/components/ClouderyView.spec.js

Those are flacky tests that often timeout on Github Action CI
We didn't find a way to stabilise them yet, so until a solution is found we want them to be disabled
Related commit: 3cb78493449dc5795ebb152c512502b702820440

fix: Disable ClouderyView tests that timeout

---

CHANGELOG.md
android/app/build.gradle
ios/CozyReactNative/Info.plist
package.json

This PR
- updates the App version to 1.0.8
- creates a new entry for next 1.0.9 release in the CHANGELOG

feat: Bump app version to 1.0.8

---

src/screens/login/LoginScreen.js
src/screens/login/OnboardingScreen.js
src/screens/login/components/functions/getInstanceDataFromRequest.ts

`getInstanceFromFqdn` returns a strings containing the Cozy instance
As this is a string, the following lines would throw when calling `url.host` and `url.origin` from a string
New `getInstanceDataFromFqdn` method returns an object containing the Cozy FQDN and instance

fix: Call correct method after receiving login and onboarding links

---

src/screens/login/LoginScreen.js

With previous implementation we would return to the PasswordView when canceling the MagicLink authorization and 2FA steps
This should not be possible because PasswordView should never appears in the MagicLink scenario, so we want to return to the WelcomeScreen instead

fix: Return to WelcomeScreen when canceling MagicLink login

---

src/screens/login/components/ClouderyView.js

When login using OIDC, then the Cloudery redirects to the app with an URL containing a `default_redirection` parameter
This parameter is already parsed by the processOIDC method, but we did not propagate the value so the Flagship can display the correct cozy-app after the Login step
Related commit: 64b24f978aa4a0740b4920a9a9d09136ec9a1017
Related commit: f0f7bfebbad3f31dd171f70b94d3c9ab7c87aa0b

feat: Use `default_redirection` param to open default app on Login

---

src/libs/clientHelpers/oidc.ts

This reverts 770c27d1eafc6e70a06bb93b934837817aa1139b since the previous behaviour was a bug that has been fixed on cozy-stack side
Now the OIDC 2FA process correctly returns a 401 error on first attempt and then all attempts with a 2fa code would produce a 403 error
Related PR: cozy/cozy-stack#3895
Related commit: 770c27d1eafc6e70a06bb93b934837817aa1139b

fix: Correctly distinguish 401 and 403 errors on OIDC 2FA

---

src/components/webviews/jsInteractions/jsCozyInjection.js

This PR addresses an issue with the immersive behavior when closing UI modals in the webview. The change consists of updating the `immersiveRoutes` array in `jsCozyInjection.js` to include both `home` and `default` routes.
The issue was caused by the name of the "home" route being changed to "default". By updating the `immersiveRoutes` array to contain both the old (`home`) and the new (`default`) route names, we ensure that the immersive behavior is maintained for both routes. This fix will revert the Operating System icons to white when closing UI modals, providing a consistent user experience.

fix: update immersiveRoutes

---

package.json
src/libs/Launcher.js
src/libs/Launcher.spec.js
src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js
src/libs/keychain.js
src/libs/keychain.spec.js

Now, when running a clisk konnector, we first check that the accounts
associated to its credentials still exist in cozy database.
If some accounts in credentials do not exist, it  means that the
associated accounts have been removed from cozy database and then we can
clean the corresponding credentials.
To make this possible, credentials are now saved with the following
format :
```
{
version: 1, // to make future migrations easier
createdByAppVersion: '0.1.0-9999',
createdAt: '2023-04-18T16:20:46.103Z',
slug: 'konnectorslug', // to find credentials associated to a given konnector slug
credentials: {
// any object given to saveCredentials
}
}
```
With this new credentials format, old format credentials are now
ignored.
If some credentials have been removed, it means that we must logout …

feat: Logout clisk webview if some account removed

---

ios/CozyReactNative/Info.plist

UINewsstandIcon has been added automatically by XCode when I added "Icon files (iOS 5)". But it is not useful and caused app to be rejected from store.

fix: Remove UINewsstandIcon from Info.plist

---

src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js
src/libs/bridge/ReactNativeLauncherMessenger.js
src/libs/konnectors/sendKonnectorsLogs.ts
src/screens/konnectors/LauncherView.js

In some cases, we still had the following message :
"nodeHandle expected to be non-null"
This was a regression after #751
In the case a webview reload was forced :
Ex : when the clisk konnector does :
```javascript
await this.goto(url)
await this.runInWorker('any  command')
```
The goto command resolved when the worker webview was not ready yet and
the launcher did not have a reference to the new webview yet.
Now, the goto command waits for the webview reference to be ready to be
resolved.
Also solve some minor issues I found during the debug
- fix: Resolve setWorkerState only when webview reference is ready
- fix: Do not create a new binded function on each message
- fix: Display the number of logs we try to send to the cozy stack
- feat: Format messenger debug message
Before merging …

fix: Resolve setWorkerState only when webview reference is ready

---

src/constants/dev-config.ts
src/core/tools/dev.ts
src/core/tools/env.ts
src/libs/ReactNativeLauncher.js
src/libs/bridge/ReactNativeLauncherMessenger.js
src/screens/home/HomeScreen.tsx
src/screens/konnectors/CliskDevView.jsx
src/screens/konnectors/LauncherView.js

Before we resolved the goto when the webview was reload but but it fails
when running goto twice in a row for example (and also in other cases on
slow devices).
Also added some enhancements on post-me logs display
- feat: Do not log non post-me messages in messenger
- fix: Call the listener when non null
- fix: Show requestId even when = 0
- feat: Better display of handshake logs
- feat: Hide log events

fix: Resolve goto when the bridge is ready

---

src/screens/login/LoginScreen.js

When login by MagicLink, the user receives an email
When the email's link is clicked, then the user is redirected to the Flagship app and then the login starts
During this phase, the App will do the login HTTP requests in background and then redirect the user to the home screen (or 2FA screen if needed)
During this phase the user will see the welcome screen (or sometimes the post code screen) until all login HTTP requests are done
Instead of this we want the user to see a loading screen

fix: Show a loading screen after opening a MagicLink

---

src/screens/login/components/CozyLogoScreen.tsx
src/screens/login/components/functions/clouderyThemeFetcher.ts
src/screens/login/components/transitions/TransitionToPasswordView.js

In some environments `getComputedStyle().getPropertyValue()` would return a result with a leading space
In this scenario we retrieve ` normal` instead of `normal`
So we want to `trim()` the result
Note that `getComputedStyle().getPropertyValue()` always return a string even if the property does not exist. In that cas the string is empty. So we don't need to check for nullity
We lost this security on feature rework when fetching Theme instead of Background

fix: Use `trim()` on `tryProcessClouderyThemeMessage`

---

src/libs/notifications/notifications.ts

When Google Play Services are not installed on Android, getToken throws errors. We can do nothing about it so we catch them silently.
Possible errors :
MISSING_INSTANCEID_SERVICE
SERVICE_NOT_AVAILABLE

fix: Catch missing Google Play Services notification error

---

ios/CozyReactNative.xcodeproj/project.pbxproj

I was not able to run the debug build on my real iphone because the profil & cert were not for debug purpose.
So we added a new provisioning profile "amiral-dev-profile". You can add a new device to this profile by going to the developper apple website.
And since we added a profile for dev purpose we needed to create a dev certificat. This certificate is available in the password store

fix: Run Debug on real Device

---

src/libs/Launcher.js
src/libs/client.js
src/screens/konnectors/LauncherView.js

The injection of credentials is needed when you want to test the
execution of a clisk konnector with an unauthenticated webview but with
saved credentials easily without having to wait for the end of website
session.
To do that you need to:
- set the flag test.flagship.clisk.credentials.injecter to true
- import the credentials in the doctype io.cozy.test.credentials with
the following form :
```javascript
{
"_id": "edf", // the slug of the targetted clisk konnector,
"value": {
"login": "login to import",
"password": "password to import"
}
}
```
Thi this setup, in the next run, the konnector will have the following
credentials available :
```javascript
{
"login": "login to import",
"password": "password to import"
}
```
When injected, the credentials will be removed from the database. …

feat: Allow to inject credentials in the flagship app

---

src/redux/KonnectorState/KonnectorLogsSlice.ts

Since the stack expects them to be strings.
Or else when for example you log an int in a clisk konnector,
No logs will be sent to the stack anymore and the logs stored in the
flagship app will grow indefinitely.

fix: Force konnector log messages as string

---

src/app/domain/scanner/services/scanner.ts

On iOS, we can not limit the number of scan and we prefer choosing the last one instead of the first one.

feat: scanDocument return last scan instead of first

---

__tests__/jestSetupFile.js
src/app/domain/authorization/services/SecurityService.ts
src/app/view/Lock/useLockScreen.ts
src/app/view/Secure/PinPrompt.tsx
src/app/view/Secure/SetPinView.spec.tsx
src/app/view/Secure/hooks/usePasswordPrompt.ts
src/app/view/Secure/hooks/usePinPrompt.ts

Calling hideSplashScreen everywhere since it seems the HomeView fails to do it in some unknown scenarios.
Not a good long-term solution, but we need it now. Especially as it can't create side effects even if the home view hides the splash screen.
Some additional minor refactor/improvements that do not touch user/data flow have been added

fix: add hideSplashScreen fallbacks

---

src/screens/home/HomeScreen.tsx
src/screens/login/OnboardingScreen.js

This PR tries to fix white screen flickering at the end of onboarding and before displaying the secure prompt
This adds a LOADING screen during the OAuth process, and then when everything is done it displays the SplashScreen until the secure prompt is displayed
I also added some blue background to HomeScreen so no white screen is displayed when the HomeView is not rendered (i.e. when waiting for a cozy-app fallback to be displayed)
This PR require the https://github.com/cozy/cozy-flagship-app/pull/806 to be merged to work correctly as I added some `showSplashScreen()` calls

fix: Remove flickering between onboarding and secure prompt

---

package.json
yarn.lock

Gives the possibility to create sub folders in the destination folder to the clisk konnectors

feat: Upgrade cozy-clisk to 0.13.0 to get subPath

---

src/app/domain/authorization/services/LockScreenService.ts
src/app/domain/authorization/services/SecurityService.ts
src/app/view/Lock/useLockScreen.ts
src/app/view/Secure/hooks/usePasswordPrompt.ts
src/app/view/Secure/hooks/usePinPrompt.ts
src/core/tools/dev.ts
src/hooks/useAppBootstrap.js
src/hooks/useGlobalAppState.spec.ts
src/hooks/useGlobalAppState.ts
src/libs/services/NetStatusBoundary.tsx
src/libs/services/SplashScreenService.ts
src/screens/home/components/HomeView.js

This pull request refines the app's locking mechanism by centralizing its logic and improving the handling of edge cases. Here are the key changes:
1. **Refactoring:** The `globalAppState` now uses the same locking service as the `homeView`. This change eliminates potential conflicts that could arise from different services handling the lock mechanism. It centralizes the logic, making the code more maintainable and less prone to bugs.
2. **Enhanced Error Handling:** With this update, we've introduced better handling of edge cases that were previously unhandled. This includes situations where the route may be `undefined` or the time since the last activity is negative. Instead of letting these cases cause potential bugs, the app will now default to a locked state, thus improving its …

 Enhancing App Locking Mechanism and Handling Edge Cases

---

src/libs/ReactNativeLauncher.js
src/screens/konnectors/LauncherView.js

Change background from default to white
Call setFlagshipUi on workerVisible

fix: set launcherview header dark on white

---

src/app/domain/authorization/services/SecurityService.ts

We had some scenarios where no hideSplashScreen was called
from the securityService or its children.
We add a hideSplashScreen in every top level flow
so that will provide a failsafe in case some subcomponent
fails to hide splashScreen for unknown/unclear/unexpected rasons

fix: add hidesplashscreen failsafes

---

src/app/domain/authorization/services/SecurityService.ts
src/screens/home/components/HomeView.js

This PR addresses a race condition that was causing the splash screen to be hidden prematurely, leading to a partially loaded view being briefly visible to the user.
Changes:
1. Adds an optional parameter `isCallerHandlingSplashscreen` to the `determineSecurityFlow` function in the `SecurityService`. When this parameter is `true`, `determineSecurityFlow` will not hide the splash screen, leaving this responsibility to the calling component.
2. Modifies `HomeView` to pass `true` for the `isCallerHandlingSplashscreen` parameter when it calls `determineSecurityFlow`. This ensures that the splash screen is not hidden until `HomeView`'s WebView event listener receives the `hideSplashScreen` message.
This is a temporary hotfix to mitigate the immediate issue. A more comprehensive solution …

Hotfix: Race Condition on SplashScreen Hide

---

src/@types/BackHandler.d.ts
src/app/domain/authentication/models/User.ts
src/app/domain/authorization/services/SecurityNavigationService.spec.ts
src/app/domain/authorization/services/SecurityNavigationService.ts
src/app/domain/authorization/services/SecurityService.ts
src/app/view/Secure/hooks/usePasswordPrompt.ts
src/app/view/Secure/hooks/usePinPrompt.ts

In this PR, we've added additional layers of security to our React Native app to handle Android back button presses and App state changes more effectively. 
Specifically, we've:
- Created a `SecurityNavigationService` that listens for Android back button presses and exits the app if the user is currently on one of the following routes: lock screen, PIN prompt, or password prompt. This prevents users from navigating back to the previous route without successful authentication. 
- Added an AppState listener to the `SecurityNavigationService`. This ensures that we only listen for back button presses when the app is active (i.e., in the foreground). When the app goes to the background, the listener is removed to prevent unnecessary usage of resources.
- Added comprehensive unit tests to …

Improve App Security with Back Button and AppState Listeners

---

src/libs/functions/iconTable.ts
src/libs/services/NetService.spec.ts
src/libs/services/NetService.ts
src/screens/cozy-app/CozyAppScreen.Animation.tsx
src/screens/cozy-app/CozyAppScreen.functions.ts
src/screens/cozy-app/CozyAppScreen.styles.ts
src/screens/cozy-app/CozyAppScreen.tsx
src/screens/cozy-app/CozyAppScreen.types.ts

This PR introduces several improvements to our offline handling strategy. The main changes include:
- **Redirect to Home instead of Stack:** Previously, when the device was offline, the app would redirect the user to the Stack when online again. To provide an updated user experience, we've changed this functionality to redirect users to the Home screen instead.
- **Graceful Unsubscribe Event Handling:** This update ensures that the `unsubscribe` event is handled more gracefully, preventing any potential issues that could arise from calling it while undefined.
- **Removal of Navigation Reset:** We've removed the use of the navigation reset function (`reset()`) because it was causing destructive effects. Instead, we've opted for less disruptive methods of navigation. Destructive effects …

Fix: Handle Offline on CozyApp Open

---

android/app/src/main/res/values/styles.xml
src/libs/httpserver/httpServerProvider.js
src/libs/httpserver/server-helpers.spec.ts
src/libs/httpserver/server-helpers.ts

In order to avoid issues with unhandled dark modes,
we disable the DayNight compat of the app
and replace it with a Light compat only.
This will disable algorithmic darkening
Tested with forceDarkMode on WebView on a Android phone in dark theme with a dark themed chrome: the homepage is not dark despite not having a meta color-scheme

fix: forcing the light theme for the app

---

package.json
yarn.lock

This will allow Sentry to catch the certification error if it arises

feat: upgrade cozy-client to 38.6.0

---

ios/Podfile.lock
package.json
src/app/domain/sleep/services/sleep.ts
yarn.lock

Add react-native-keep-awake and wrap it in a service. Tested on Android simulator and iOS device.
This API **works** when app is **in foreground** and **until app is quit**.
```
import {
activateKeepAwake,
deactivateKeepAwake
} from '/app/domain/sleep/services/sleep'
...
activateKeepAwake()
// long task where you do not want to go to sleep
deactivateKeepAwake()
...
```

Add keep awake API

---

src/app/domain/authentication/services/SynchronizeService.spec.ts
src/app/domain/authentication/services/SynchronizeService.ts
src/hooks/useGlobalAppState.ts
src/libs/client.spec.js
src/locales/fr-FR/translation.json

This PR introduces a new feature to synchronize the device with the stack. The `synchronizeDevice` function has been added, which is responsible for synchronizing the state of the device with the backend. It's called both at the app start and whenever the app wakes up from the background.
- Added `synchronizeDevice` function in `SynchronizeService`.
- Added tests for `synchronizeDevice` to ensure its proper functioning.
- Integrated `synchronizeDevice` so that it is called at the app's start in useGlobalAppState.
- Integrated `synchronizeDevice` to be called when the app wakes up in useGlobalAppState.
1. Clone the branch.
2. Run the application.
3. Check the logs to ensure that the device is being synchronized at the start.
4. Put the app in the background and then bring it back to the …

Add Device Synchronization at App Start and Wake Up

---

__tests__/jestSetupFile.js
ios/Podfile.lock
src/app/theme/SplashScreenService.ts
src/libs/icon/icon.spec.ts
src/libs/icon/icon.ts
src/screens/login/LoginScreen.js

**fix: Flags were not fetched at login with oidc and magic link**
Solve icon not changing at first login with oidc and magic link.
**fix: Splash screen does not hide when icon has changed on iOS**
Changing icon and using splash screen do not work well together. If
we call hideSplashScreen when iOS native popup "Icon has changed" is
displayed, hideSplashScreen hides iOS native popup instead of splash
screen. So here we avoid to call changeIcon when splash screen is
displayed.

Fix icon feat splashscreen issues

---

package.json
src/libs/Launcher.js
src/libs/Launcher.spec.js
src/libs/ReactNativeLauncher.js
src/screens/login/components/ClouderyViewSwitch.tsx
yarn.lock

Now call cozy-clisk saveFiles directly for all the given files and pass
a callback which saveFiles will call when the download of a file is
needed. This downloadAndFormatFile callback downloads the given file in
the worker webview and format it to ArrayBuffer as expected by the cozy
stack.
See https://github.com/konnectors/libs/pull/949 for the related
cozy-clisk PR

feat: Download files progressively only when needed 

---

src/components/webviews/CozyProxyWebView.js
src/components/webviews/ReloadInterceptorWebView.js

The ReloadInterceptorWebView component is responsible to intercept the WebView's reload events and to remount the component instead of just doing an HTML reload
With current implementation, if the cozy-home app is in an error state due to invalid cookies, then reloading ReloadInterceptorWebView won't fix the problem as the same HTML content will be served from the CozyProxyWebView that is not re-rendered
To fix this, we want to do the reload process on the CozyProxyWebView instead, so the getIndexHtmlForSlug is called and then cookies would be refreshed

fix: Fully reload the CozyProxyWebView from ReloadInterceptorWebView

---

src/libs/ReactNativeLauncher.js
src/libs/konnectors/sendKonnectorsLogs.spec.js
src/libs/konnectors/sendKonnectorsLogs.ts
src/redux/KonnectorState/KonnectorLogsSlice.ts

When possible, we add job_id to konnectors log send to the stack.
The job is only created after the ensureAuthentificated function so, only log after that will be tagged by job_ib

feat: Add job_id in konnector log when possible

---

src/constants/strings.json
src/libs/functions/iconTable.spec.ts
src/libs/functions/iconTable.ts
src/libs/localStore/storage.ts

We can have different icons for the same slug depending on the context of your cozy.
So instead of serving the wrong one, let's clean this data on logout.
fix: Display the right Mes Papiers icons when switching between cozies.

fix: Clean IconsTable on logout

---

src/app/view/Lock/LockScreen.tsx

We don't want to autocapitalize input password field

fix: Don't capitalize password input

---

src/@types/cozy-client.d.ts
src/App.js
src/app/domain/authentication/services/SynchronizeService.spec.ts
src/app/domain/authentication/services/SynchronizeService.ts
src/hooks/useGlobalAppState.ts
src/hooks/useSynchronizeOnInit.ts
src/libs/clientHelpers/createClient.ts

This PR introduces a new function `checkClientName` and its corresponding Jest tests. The function checks if a client's name starts with a specific string, defined as `translation.software.name`, and updates the client name on the server if it doesn't. In case of any error during the update, the error message is logged. 
This PR also includes TypeScript interfaces to represent the client response object, and Jest tests to ensure that `checkClientName` works as expected.
- Created a new function `checkClientName` that checks a client's name and updates it on the server if necessary.
- Added TypeScript interfaces for the client response object.
- Wrote Jest tests for the `checkClientName` function, including tests for when the client name should be updated, should not be updated, and when …

feat: save oauthName on app bootstrap if needed

---

src/screens/login/components/ClouderyCreateInstanceView.js
src/screens/login/components/ClouderyViewSwitch.tsx

These webviews were apparently the only ones left without an
userAgent set in the webview.

fix: add UA on Cloudery webviews

---

src/libs/Launcher.js
src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js
src/screens/konnectors/LauncherView.js

- expose the `queryAll` method from the launcher to the konnector
- add current account, trigger, manifest, job, sourceAccountIdentifier to the context given to the `fetch` method.
Linked to https://github.com/konnectors/libs/pull/952 for the cozy-clisk side

feat: Add more context to konnector execution

---

src/libs/client.spec.js
src/libs/clientHelpers/authorizeClient.ts
src/libs/clientHelpers/connectClient.ts
src/libs/clientHelpers/createClient.ts
src/libs/clientHelpers/initClient.ts
src/libs/clientHelpers/magicLink.ts
src/libs/clientHelpers/oidc.ts
src/screens/login/LoginScreen.js

Those methods were missing from the MagicLink and OIDC login processes
Without them:
- the `client.emit('login', ...)` would never be called and so CozyClient's plugins would not be initialized, which would produce infinite await on `client.plugins.flags.initializing` on LoginScreen
- the client would not be persisted
- the TokenRefresh event wouldn't be handled
This happens only on production environment and on Flagship certified devices. Otherwise, the manual certification workflow would correctly call those methods

fix: Call login, saveClient and listenTokenRefresh on magicLink and OIDC

---

src/libs/Launcher.js
src/libs/ReactNativeLauncher.js
src/screens/konnectors/LauncherView.js
src/screens/konnectors/LauncherView.spec.jsx

when activated, display a view juste above the worker but not above the "Return to my cozy" link.
See https://github.com/konnectors/libs/pull/953 for the content script side
I had to set the timeout to wait for elements of LauncherView to display to 10s or else the tests would not pass on travis side.

feat: Add blockWorkerInteraction command support

---

package.json
yarn.lock

See https://github.com/konnectors/libs/pull/957

fix: Upgrade cozy-clisk to 0.20.2 to fix saveIdentity bug 

---

src/index.js

This was set up two years ago when the app was supposed to run in the browser too. That is no more the case. Hence, it seems a good idea to remove such setup in a cleanup effort.

refactor: remove unused rn-web setup

---

src/screens/konnectors/LauncherView.js

about:blank was introduced in https://github.com/cozy/cozy-flagship-app/pull/850 . It seems to work great on Android, but on iOS we got a native crash:
"NSInvalidArgumentException UIInputWindowController" see #54051 issue on sentry.
By reading the source code https://github.com/react-native-webview/react-native-webview/blob/891e595bcf5cafe4a903d5aa643e8361d0c3d467/apple/RNCWebViewImpl.m#L750-L758 it works great if we inject an html.

fix: Clisk on iOS

---

package.json
src/@types/cozy-client.d.ts
src/app/domain/backup/models/Media.ts
src/app/domain/backup/queries/index.ts
src/app/domain/backup/services/getMedias.spec.ts
src/app/domain/backup/services/getMedias.ts
src/app/domain/backup/services/manageAlbums.ts
src/app/domain/backup/services/manageBackup.ts
src/app/domain/backup/services/manageLocalBackupConfig.ts
src/app/domain/backup/services/manageRemoteBackupConfig.ts
src/app/domain/backup/services/uploadMedia.android.ts
src/app/domain/backup/services/uploadMedia.ios.ts
src/app/domain/backup/services/uploadMedias.ts
yarn.lock

- Create same folder structure for Android as on device
- Stopping backup return ready state so that we can see number of medias remaining to backup
- Fix various bugs

Backup : create folder structure for Android, fix various bugs

---

ios/Podfile.lock
package.json
src/locales/i18n.ts
yarn.lock

`react-native-localize` has been upgraded to `2.2.6` to make it
compatible with iOS `11`
After `3.0.0` this library requires iOS `12.4` and react-native `0.70`
so we should not upgrade to this version until we do the react-native
migration and chose to drop iOS `11` support
Also `Intl` is only provided on Android's Hermes but is not available on iOS
so we should add a polyfill to use it

fix: Make i18n work on iOS

---

package.json
yarn.lock

See https://github.com/konnectors/libs/pull/958

fix: Upgrade cozy-clisk to 0.20.3 to avoid an error message

---

src/screens/konnectors/LauncherView.js

And convert it to a change of url in the worker.
I suppose this is the expected behavior for every konnector we have at the moment or else we may make it optional.
This is needed for the sncf konnector login but we still have to check if this does not affect other konnectors regarding the download of files and this is why this PR is still draft
We also will have to check if this works as expected on iOS

feat: Intercept window.open in worker

---

src/app/domain/navigation/webviews/UrlUtils.spec.ts
src/app/domain/navigation/webviews/UrlUtils.ts
src/components/webviews/CozyWebView.js
src/constants/strings.json

**Addition of new URL schemes**: We have extended our URL handling capabilities by including more URL schemes - mailto:, tel:, sms:, maps:, and geo:. This allows our application to support a wider range of user interactions directly within our WebView.
**Refactoring origin whitelist into constants**: For better maintainability and readability, we have moved the origin whitelist URL schemes into a separate constant into the `strings` JSON file. The ORIGIN_WHITELIST constant can now be imported wherever it is needed, promoting better code organization and reducing the potential for error.
**Integration with existing openUrl() function**: The enhanced URL scheme handling uses our existing openUrlWithOs() function, ensuring that all non-HTTP/HTTPS URLs are safely handled by the appropriate …

feat: enhance cozywebview URL scheme handling

---

package.json
src/App.js
src/app/theme/SplashScreenService.ts
src/hooks/useSplashScreen.ts
yarn.lock

We want the app to correctly hide the new `secure_background` SplashScreen when the app goes active
The `secure_background` is a new SplashScreen that is displayed when the app is on OS background so the app's content is hiden when in this state
> **Note**
> All other `showBackground` and `hideBackground` don't take a name argument, so the default name is `global` (cf cozy/react-native-bootsplash#1 description)
Related PR: cozy/react-native-bootsplash#1
___
TODO:

fix: Handle hiding `secure_background` SplashScreen

---

src/libs/ReactNativeLauncher.js

- Log error result of a konnector execution, to see the error in logs even if the error occurs before authentication
- Send logs to stack even when no job is created (theses logs are useful and will be sent by the flagship app later anyway)

feat: More logs in konnectors

---

package.json
yarn.lock

To fix konnectors file download when download is done from the launcher.

fix: Upgrade cozy-clisk to 0.22.2

---

src/app/domain/backup/hooks/useInitBackup.tsx

When checking at startup if a backup is running, it was throwing an error if there was no backup. We should just do nothing if there is no backup.

fix(backup): Avoid to throw error at startup when no backup

---

__tests__/jest.config.js
__tests__/jestSetupFile.js
ios/Podfile.lock
package.json
src/app/domain/backup/helpers/error.ts
src/app/domain/backup/models/Backup.ts
src/app/domain/backup/services/manageBackup.ts
src/app/domain/backup/services/manageLocalBackupConfig.ts
src/app/domain/backup/services/uploadMedias.ts
src/app/domain/upload/models/index.ts
src/app/domain/upload/services/upload.android.ts
src/app/domain/upload/services/upload.ios.ts
src/libs/notifications/notifications.ts
src/locales/en.json
src/locales/es.json
src/locales/fr.json
yarn.lock

- Improve error management in backup and upload services
- Backup service displays a local notification when a backup is a success
- Backup service return a last backup data to front end (see https://github.com/cozy/cozy-drive/pull/2970)

Backup: Errors and notifications

---

package.json
src/libs/ReactNativeLauncher.js
yarn.lock

See https://github.com/konnectors/libs/pull/964, this check was done at
contentscript level at first but we also need this check at the launcher
level.
If this check is not done, the flagship app will be stuck trying to send logs and get an error from the stack because the log level is unknown

feat: Check log allowed level

---

src/app/domain/backup/services/manageBackup.ts
src/app/domain/backup/services/uploadMedias.ts
src/locales/en.json
src/locales/es.json
src/locales/fr.json

On iOS, it is not supported.
On Android, it is supported until Android 11 because android-upload-service uses Service to start foreground task in background which is deprecated since Android 12.

fix(backup): Stop background backup when not supported

---

.github/workflows/build-ios-dev.yml
.github/workflows/build-ios-prod.yml

In 3b14bdb041d659addd79aa4883249f55cbf2acba we triggered the pods installation from yarn's `postinstall` event
The impact is that the pod cache should now be restored before calling `yarn install`
This would reduce the worlkflow duration by 5 to 10 min
This commit also move the Ruby installation before the `yarn install` so the CI steps are grouped in the following order:
- Environment installation
- Cache restoration
- Dependencies (node and pods) installation
- Build phase
Related commit: 3b14bdb041d659addd79aa4883249f55cbf2acba

fix: Restore pod cache before installing node_modules on IOS CI

---

src/screens/konnectors/LauncherView.js

We had a problem with the MGEN clisk which, when we set with and height to 0, caused the website to loop infinitely. Because of this loop, the worker could be killed.
In order to stay as close as possible to the user experience when a clisk is launched, we decided to set the with and height to 100%.

fix: Do not set the size of the worker to 0 when hidden

---

src/hooks/useSplashScreen.ts

The `secure_background` SplashScreen is meant to be displayed when the app is sent to OS background, then to be hidden when the app becomes active again
When starting the app, the `secure_background` should not be displayed, so we did not try to hide it when implementing this feature
But we encountered a bug that would happen when the "change icon" mechanism occurs on Android
When this happen, if the app is sent to background, then the `secure_background` is displayed and then the app is killed (or maybe it is just the app's main activity but not the entire app?). Then when the user re-open the app, the react-native code is executed like if it was an app's startup, but in fact the app is still in the previous state with the `secure_background` SplashScreen is displayed. And because the …

fix: Hide `secure_background` SplashScreen on app start

---

white_label/brands/mabulle/js/constants/strings.json

In #930, we unexpectedly removed `2F` from the Cloudery url in the MaBulle version

fix: Add missing `%2F` in MaBulle Cloudery url

---

android/app/src/main/java/io/cozy/flagship/mobile/MainActivity.java

PlayStore console reported some crashes related to react-native-screens that are related to Activity's `onCreate` method
This bug is well documented in the react-native-screens repository and the recommended action is to discard the Activity's persisted state when restarted
This is because the JS state (redux stores, in-component state etc) is not persisted the same way as the Android activity state, so there can be some inconsistencies between them when the app is restarted
Discarding the state implies that if Android kills the Activity when app is on background, then on when going back to the app it will behave like if it was a fresh start
Another impact is for foldable phones in which the app will restart when splitted into multi-window. But as the app does not support this mode, then …

fix: Discard persisted state on Android Activity restart

---

src/screens/login/components/functions/oidc.ts

We want the used scheme to correspond to the current brand otherwise doing OIDC from MaBulle would trigger the Cozy app

fix: Use scheme from `strings.json` for OIDC login

---

src/app/domain/backup/helpers/media.ts
src/app/domain/backup/services/manageRemoteBackupConfig.ts
src/app/domain/backup/services/uploadMedia.ios.ts
src/app/domain/upload/models/index.ts
src/app/domain/upload/services/index.ts

fix(backup): Change how we rename file when conflict
fix(backup): Use only name and creationDate to compare medias

Backup renaming

---

white_label/brands/mabulle/js/constants/extra-strings.json

We want the Cloudery to be able to display info specific to current brand
So when the Flagship app differs from the Cozy version we add the `flagship_app` param with the brand name
If the parameter is not provided, then the Cloudery defaults to Cozy version

feat: Pass `flagship_app=mabulle` param to the Cloudery web page

---

src/app/domain/backup/queries/index.ts
src/app/domain/backup/services/manageBackup.ts
src/app/domain/backup/services/manageLocalBackupConfig.spec.ts
src/app/domain/backup/services/manageLocalBackupConfig.ts
src/app/domain/backup/services/manageRemoteBackupConfig.ts

Goal : add a backup which upload only what is NOT already in the whole cozy. This is a first version we want to try on real data/user.
Technically, before all backup :
- fetch all media from Cozy
- compare them with local media with name and creation date
- if media exists on phone AND is not already considered as backup, we considered it as backup
=> avoid to upload media already present it cozy
Behind a flag('flagship.backup.dedup')

Dedup first version

---

src/app/view/Manager/useManagerScreen.ts
src/screens/login/LoginScreen.js
src/screens/login/components/functions/oidc.spec.js
src/screens/login/components/functions/oidc.ts

When entering an email linked to an OIDC Cozy, the received email will open the Manager that will then redirect to OIDC Oauth
Previous implementation did not support this scenario
When this scenario is detected, then the Manager should redirect to the Authentication screen that will trigger the OAuth process

feat: Implement email login for OIDC accounts

---

src/app/domain/limits/OauthClientsLimitService.spec.ts
src/app/domain/limits/OauthClientsLimitService.ts
src/app/domain/limits/checkOauthClientsLimit.spec.ts
src/app/domain/limits/checkOauthClientsLimit.ts
src/app/view/Limits/OauthClientsLimitExceeded.tsx
src/app/view/Limits/hooks/useOAuthClientsLimitExceeded.ts
src/components/webviews/CozyProxyWebView.js
src/screens/home/HomeScreen.tsx

Cozy-stack will now limit the number of registered OAuth clients based on `cozy.oauthclients.max` flag
On web, when the limit is reached and the user tries to open a cozy-app then the browser is redirected to `/settings/clients/limit-exceeded`
On Flagship app, we want to intercept this mechanism in order to keep control on how application behaves
To handle this we manually do the limit check in `CozyProxyWebView` before initializing HTML content. This would allow us to handle both Stack and HttpServer based cozy-apps
Then we display a dedicated WebView that will display the `/settings/clients/limit-exceeded` route from cozy-stack
Also we chose to always display cozy-home even if the limit is reached. This is possible because cozy-home is always served from the local HttpServer and this …

feat: Implement OAuthClientsLimitExceeded dialog

---

src/app/view/Limits/hooks/useOAuthClientsLimitExceeded.ts

This button should not be displayed until we enable InAppPurchase
To hide it we want to pass the `isFlagship=true` parameter to the `/settings/clients/limit-exceeded` page. Then the cozy-stack will not render the button until we enable InAppPurchase
Related commit: 299968d43914066c3147276eea2463ebb292d527

feat: Hide `See offers` button on `OauthClientsLimitExceeded` popup

---

src/app/domain/limits/OauthClientsLimitService.ts
src/app/domain/navigation/webviews/UrlService.ts
src/app/view/Limits/hooks/useOAuthClientsLimitExceeded.ts

In some edge-case scenario, the app may incorrectly open a cozy-app even if the OAuth client limit is exceeded
This may happen if the `cozy.oauthclients.max` flag is not set when the app starts but it is set just after that. In that case, the limit check won't be done when the user tries to open a cozy-app because flags are not updated after the app start. This is an edge case of a8ad127b0349715db75b11b6c411df6feb2ff1fe
This may also happen if some network errors occur when querying the cozy-stack for doing the check. In that case the app will fallback to an "under the limit" scenario
In those cases, the app will tries to open the cozy-app and then the cozy-stack will return a `302` to `/settings/clients/limit-exceeded`
With current implementation, this `302` will be intercepted by the …

fix: Intercept redirection to `/settings/clients/limit-exceeded` page

---

src/components/webviews/CozyProxyWebView.functions.js
src/components/webviews/CozyProxyWebView.js
src/components/webviews/CozyProxyWebView.spec.js

When showing OauthClientsLimitExceeded we should ensure that a Session Cookie is set on the app
If not, the popup will display a cozy-stack error
After the login scenario, when cozy-home does its first render, then no Session Cookie exist yet. In that case we should call `getIndexHtmlForSlug` at least once to generate the Session Cookie
So in that case we want to call `showOauthClientsLimitExceeded` only after `getIndexHtmlForSlug`
But if a Session Cookie exists, then we want to continue doing the check before calling `getIndexHtmlForSlug` so we prevent unnecessary `getIndexHtmlForSlug` calls (this queries cozy-stack) when OauthClientsLimit is exceeded and when the Session Cookie exists

fix: Call showOauthClientsLimitExceeded only when Cookie exists

---

src/libs/functions/routeHelpers.ts

The `warn` level generates too much noise on the debuging console as it outputs the entire stack trace
The 🚨 icon used in the log is enough to catch the attention so we now want to use `debug` log

fix: Log `checkInitialParam` alert using `debug` level instead of `warn`

---

android/build.gradle
ios/Podfile
ios/Podfile.lock
package.json
src/app/domain/ocr/services/ocr.ts
src/libs/intents/localMethods.ts
yarn.lock

We want cozy-apps to be able to call OCR on a base64 image
The flagship now exposes two new methods through cozy-intent:
- `isOcrAvailable`: Check if the OCR feature is supported by the current app
- `ocr`: Process OCR on the given base64 image and return the OCR result + the image size
Related PR: cozy/cozy-libs#2297
___
TODO:

feat: Add OCR support for cozy-apps

---

src/libs/ReactNativeLauncher.js

When an error occured in the preparation phase of a clisk konnector
(ensureAuthenticated, getUserDataFromWebsite), we got an empty error
message.
This is fixed, and we could have detected it with ts-check header in the
file. This will come in another PR, since there are many problems to
fix when ts-check is activated.

fix: No more empty message when error before fetch

---

src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js

Or else, if the konnector does not return any sourceAccountIdentifier,
the account and trigger will be created and the execution will fail when
trying to create the desination folder, which makes it harder to link
with the missing sourceAccountIdentifier.

fix: Ensure sourceAccountIdentifier is present in getUserDataFromWebsite return value

---

white_label/brands/mabulle/js/locales/extra-en.json
white_label/brands/mabulle/js/locales/extra-es.json

In #936 we added some custom texts for french version of Ma Bulle that were not declared on english and spanish versions
When this is the case, then the Cozy version of those texts is used
Here we want to have Ma Bulle specific texts for those languages
> **Warning**
> Those are auto-translated versions. I checked the English result, but I can't check the spanish version as I don't speak spanish

feat: Set missing translations for Ma Bulle

---

src/libs/ReactNativeLauncher.js

from debug.clisk.html-on-error to clisk.html-on-error in order to follow our internal convention

fix: Change flag name

---

src/app/domain/geolocation/tracking/index.js
src/libs/localStore/storage.ts

Allow to set custom values for three geolocation tracking parameters. Store them in local storage.
No breaking change.

feat: Allow to customize tracking config for geolocation tracking

---

README.md

Since we didn't have a props to inspect the webview yet, and since iOS 16.4 we need to add code manually, let's document it.

docs: Add instruction about how to inspect the webview

---

src/app/domain/geolocation/tracking/tracking.js

e-mission uses timestamp divided by 1000

fix: Start transition timestamp

---

src/screens/login/components/ClouderyViewSwitch.tsx

In previous implementation, both Signing and Login WebViews were loaded in parallel
When doing this, there was a race condition on the Cloudery that would create two new sessions in parallel and so two different cookies instead on a single one
Later in the process, this would occasionally produce some CSRF issues due two the co-existence of two cookies, resulting in a 422 error from the Cloudery
To prevent that, we want both WebViews to be loaded sequentially to ensure only the first WebView will create a new session on Cloudery
This should be a bit slower, but this is acceptable

fix: Load ClouderyViewSwitch's WebViews sequentially

---

src/libs/notifications/notifications.ts

If we set a redirectLink to home from a notification, it was redirecting to home app in the cozy app screen. But we want home app to always be in home screen.

fix: Navigate to home from notification

---

src/app/domain/geolocation/services/permissions.ts

ACTIVITY_RECOGNITION permission has been added in Android 10. So asking it result to an "Permission unavailable" error on Android < 10.

fix(geolocation): Do not ask for ACTIVITY_RECOGNITION permission in Android < 10

---

src/app/domain/backup/services/manageAlbums.spec.ts
src/app/domain/backup/services/manageAlbums.ts
src/app/domain/backup/services/manageBackup.ts
src/app/domain/backup/services/uploadMedias.ts

Previously, we created every new album at beginning of backup, which
lead to two issues :
- backup preparation time was long when you had a lot of albums (and
indirectly no button was shown on front end side)
- if you stop a backup, you can have empty albums because album has
been created but media not uploaded
Now, an album is created only when a media in this album  has been
uploaded.
--- 
First commit are refactoring.

Create album only when a media in this album is uploaded

---

package.json
src/components/webviews/jsInteractions/jsCozyInjection.js
src/libs/intents/localMethods.ts
yarn.lock

**refactor: Support 'ocr' feature in isAvailable**
We decided to move from isFeatureAvailable() to isAvailable(featureName: string) to check if a feature is available.
isOcrAvailable has not been released yet. So let's move it now before having to handle a breaking change.
**refactor: Support 'scanner' and 'backup' feature in isAvailable**
We decided to move from isFeatureAvailable() to
isAvailable(featureName: string) to check if a feature is available.
These feature have already been released in production. So I add the
possibility here to check if they are present by calling
isAvailable('scanner') or isAvailable('backup') but I do not remove
isScannerAvailable method and backup_available injected variable.
We will need to wait that the new isAvailable is released and
distributed to all …

Add 'ocr', 'scanner' and 'backup' features to isAvailable

---

src/app/domain/geolocation/tracking/index.js

tracking
These errors were silently catched by the app. We want to show them in debug, and send them to sentry when a real user can not enable or disable geolocation.

fix: Display and send to sentry logs when unable to start/stop

---

src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js
src/screens/konnectors/LauncherView.js

No error in harvest will be shown in harvest when the user stops the
execution of the konnector himself.
An error log will still be generated to keep a trace of those execution
stops which may result from multiple causes :
- the user has wrong identifiers
- the konnector does not detect authentication correctly
- or any other unpredicted cause

feat: Do not show an error in harvest on stopped by user

---

src/libs/intents/setFlagshipUI.ts
src/screens/home/HomeScreen.tsx
src/screens/konnectors/LauncherView.js

We had multiple cases where white on dark or dark on white icons
were displayed.
To handle that, we:
- Removed auto light statusBar in homeScreen
- Made more explicit launcher views calls
- Improved Theme logging to detect issues with more ease

fix: Remove cases where UI was unstable in Harvest

---

src/components/webviews/CozyProxyWebView.js
src/screens/home/HomeScreen.styles.ts
src/screens/home/HomeScreen.tsx

On Android and on small screen, some cozy-app fields may be hidden behind the keyboard when it is open
This can happen on Harvest unlock form, in MesPapiers when adding some documents, or in cozy-notes when editing a text on the bottom of a note
To prevent this we want to add a `KeyboardAvoidingView` around cozy-app WebViews like it is already done for login, onboarding and lock screens
Also, in the addition of `KeyboardAvoidingView`, we need to remove the `justifyContent: 'center'` on the HomeScreen. With this value the HomeView would stay center in the screen referential when the keyboard is open, so the HomeView would become partially hidden by the keyboard and would have a large padding on its top
Removing `justifyContent: 'center'` on the HomeScreen seems to have no side effect. This …

fix: Make cozy-apps responsive to keyboard on Android

---

src/app/view/OsReceive/OsReceiveScreen.logic.ts
src/app/view/OsReceive/OsReceiveScreen.tsx

The goBack function wasn't behaving as expected
(trying to load the previous cozy-app that was in use).
In the meantime it was decided to scrap this functionality.
The user can still go back with his device controls

fix: remove back arrow in osReceiveScreen

---

src/app/domain/authorization/services/SecurityService.ts
src/app/domain/osReceive/services/OsReceiveData.ts
src/libs/RootNavigation.js

This helps removing race conditions on app start
when React starts listening to received files too late
(which means we don't receive them at app start)

fix(receive files): Improve app wake-up side-effects

---

src/app/domain/geolocation/tracking/storage.js
src/app/domain/geolocation/tracking/tracking.js
src/app/domain/geolocation/tracking/tracking.spec.js
src/app/domain/geolocation/tracking/upload.js
src/app/domain/geolocation/tracking/utils.js

- Change activities filtering strategy: we now exclude consecutive stationary activities, and when their confidence is low.
- Code refactoring to simplify the processing before upload and avoid edge cases
- Exclude network locations occuring after last stationary event, that was extending trip duration

Improve trip segmentation

---

android/app/src/main/java/io/cozy/flagship/mobile/MainActivity.java

Some apps like "Files by Google" were opening the app
multiple times through intent creation, this led to huge issues.
We now check on create how the app was launched and force it
to stay in main activity at all times

fix: Avoid multiple app instances creation

---

src/libs/Launcher.js
src/libs/Launcher.spec.js

This happens when some files on the cozy do not have the metadata
attribute. Now the files without metadata will be replaced.

fix: Cannot read property 'fileIdAttributes' error

---

android/app/src/main/java/io/cozy/flagship/mobile/MainApplication.java
android/gradle.properties

Fix backup issues resulting in "Backup config not initialized" errors
Read limit per entry : 2MB to 50MB
Write limit per whole app: 6MB to 100MB

Increase AsyncStorage read and write limits

---

README.md
package.json
src/App.js

2 plugins were installed to debug AsyncStorage with flipper : rn-async-storage-flipper to view and
rn-flipper-async-storage-advanced to edit.
When updating to rn-flipper-async-storage-advanced to 1.0.8 (see https://github.com/lbaldy/flipper-plugin-async-storage-advanced/pull/9), we do not need anymore both plugins.
You need to update rn-flipper-async-storage-advanced on Flipper side.

feat: Remove not useful anymore rn-async-storage-flipper

---

yarn.lock

I forgot to commit the yarn.lock here https://github.com/cozy/cozy-flagship-app/pull/1004/files

fix: Update yarn.lock after removing rn-async-storage-flipper

---

patches/@react-native-camera-roll+camera-roll+5.7.2+001+return-local-id.patch
src/app/domain/backup/helpers/error.ts
src/app/domain/backup/models/Media.ts
src/app/domain/backup/queries/index.ts
src/app/domain/backup/services/getMedias.ts
src/app/domain/backup/services/manageRemoteBackupConfig.ts
src/app/domain/backup/services/uploadMedias.ts

Add idFromLibrary and creationDateFromLibrary in io.cozy.files metadata for backup
=> these id and date will never be changed by the stack so we can trust them
=> it will solve issues where two identical pictures were not seen as identical by the backup because the date was changed by the stack
Also changes the way we send metadata
I will create a PR later for react-native-camera-roll

Add idFromLibrary and creationDateFromLibrary in io.cozy.files metadata for backup

---

src/app/domain/osReceive/services/OsReceiveCandidateApps.ts

fix: add appname when incompatible mime

---

src/components/webviews/CozyProxyWebView.js
src/screens/cozy-app/CozyAppScreen.tsx

The `KeyboardAvoidingView` component struggles to adapt to Ui layout changes
With previous implementation, the one on `CozyAppScreen` would offset the View using the wrong values
This is because it is initialized while the `isFirstHalf` variable being false, and so when the `dimensions.statusBarHeight` is applied on top of the View, then the `KeyboardAvoidingView` won't notice the change
To prevent this, we want to avoid any change in the UI layout, and so we want the `Animation` to have no impact on it
This can be done by moving it outside of the main View
When using `KeyboardAvoidingView` we need to apply `keyboardVerticalOffset` based on the offset between the View that needs to react to keyboard and the top of the screen
Otherwise, the View wouldn't move enough when keyboard is …

fix: Correctly display cozy-apps when the device's Keyboard is displayed

---

src/app/view/OsReceive/OsReceiveScreen.tsx

We only show the first reason for the app being disabled in the view.
We do not trim the reasons array earlier,
because it could be useful to have the other reasons still
available for debugging or other purposes.

fix: only show first disabled reason in sharing

---

src/app/view/OsReceive/OsReceiveProvider.tsx

With current implementation, the native plugin would trigger `receiveFiles` event everytime the app is sent to background then foreground. This would reset the "send file" scenario even if the user chose a cozy-app to receive files
By calling `OsReceiveEmitter.clearReceivedFiles()` we ensure the event won't be sent again until a new share is done by the user
This commit relies on the
`@mythologi+react-native-receive-sharing-intent+2.2.1.patch` patch that modifies the `OsReceiveEmitter.clearReceivedFiles()` behaviour
Related commit: d23cbcd1ab171b5d55b6c00f89a37bda52a213e9
Thanks to @Ldoppea & @acezard for their help ❤️

fix: Reset the send file scenario when switching to background (android)

---

src/app/domain/deeplinks/services/DeeplinksParserService.spec.ts
src/app/domain/deeplinks/services/DeeplinksParserService.ts

With current implementation, when clicking on a login email, if the app is already connected to a Cozy, then the app tries to open a cozy-app with that link
We don't want that to happen as it would produce an error and also this is not an expected scenario
To prevent that we want to ignore links that start with a scheme or manager links
Note that this implementation is not bullet proof. Instead of preventing forbidden URLs we should instead hande only authorised ones. This should be done in another commit
Also this bug highlighted another bug: when the login by email scenario ends and when the flagship certification is automatic, then the Linking `url` event is triggered another time (in useAppBootstrap). So this would trigger the navigation to a cozy-app
By ignoring manager links we …

fix: Do not intercept manager and scheme links in cozyAppFallbackURL

---

package.json
src/libs/Launcher.js
src/libs/Launcher.spec.js
yarn.lock

When this even occurs, it means that the main destination folder of the
konnector has been removed during konnector execution.
In this case, we :
- Regenerate the files index
- create the destination folder according to the manifest
- update the trigger with the new message.folder_to_save attribute
- retry saveFiles
see https://github.com/konnectors/libs/pull/973
Still needs https://github.com/konnectors/libs/pull/973 to be merged and the resulting version of cozy-clisk to be added.

feat: Handle MAIN_FOLDER_REMOVED error on saveFiles

---

src/App.js
src/components/webviews/jsInteractions/jsCozyInjection.ts
src/hooks/useGlobalAppState.ts

This will removes error logs at app start when jsCozyInjection
was trying to get routeName too fast in the app cycle.
Now it will go through the getCurrentRouteName facade
which handles non-ready nav objects.
Also remove unused injections linked to navigation in useGlobalAppState

fix: don't call getCurrentRoute if nav isn't ready

---

src/app/view/OsReceive/OsReceiveProvider.tsx

This is triggering unecessary rerenders elsewhere in the app
when the user doesn't has files to upload.
Instead we fetch registry if we detect presence of files.
It might be slower in file upload scenario, but it cleans up a lot
app start rerenders (file upload state is linked to localMethods)

fix: don't fetch for candidateapps at start

---

src/libs/Launcher.js
src/libs/ReactNativeLauncher.js

We did not have a "Konnector failure: ..." log when an error happened before the fetch step (ensureAuthenticated, getUserDataFromWebsite) and when the account, trigger and job did not exist yet
Since we use this log to supervise the execution of clisk konnectors, we need it in this case too.
- fix: Log Konnector failure log on errors before fetch
- fix: Wrong message attribute in launcher logs
- fix: Some ts-check lint errors

fix: Log Konnector failure log on errors which occur before fetch step with no account

---

src/app/domain/authorization/services/LockScreenScenarios.md
src/app/domain/authorization/services/LockScreenService.spec.ts
src/app/domain/authorization/services/LockScreenService.ts
src/app/domain/authorization/services/SecurityService.ts
src/app/view/Secure/PinPrompt.spec.tsx
src/constants/dev-config.ts
src/core/tools/env.ts
src/libs/functions/getErrorMessage.ts
src/locales/en.json

This pull request includes changes to the `validatePassword` function in the lockscreen feature. The function now handles several scenarios, including successful validation with cached password, successful validation with user input password, invalid cached password and invalid user input, unexpected server errors, errors in the success handler, and network or communication errors. These changes improve the overall user experience and ensure that the lockscreen feature is more reliable and secure.

Improve password change scenario in lockscreen

---

src/screens/home/components/HomeView.js

If the default app is not home and the files are received too quickly,
the backToHome() call will happen before the navigate to
cozyapp from lockscreen.
we can bypass that by checking at a later time if we should
go to the cozyapp or not based on filestoupload presence

fix: handle race condition with default app

---

src/screens/cozy-app/CozyAppScreen.Animation.tsx
src/screens/cozy-app/CozyAppScreen.functions.ts

Width has to be null at start even if it's not a valid value
(was set to undefined and it broke the progress bar)
At the time of this fix we want to go back the previously working value
but we have to investigate why it has to be null

fix: revert animation width to previous value

---

src/components/webviews/jsInteractions/jsLogInterception.ts

We still want to send the console.warn() from the flagship app to sentry, but we don't want to send the console.warn coming from the WebApp to sentry. It makes too much noise and since we can't fix them from the flagship app, we don't need to send them. They should be already sent by the wepabb to its own sentry.

fix: Convert JSInterception console.warn to log

---

__tests__/jestSetupFile.js
src/app/view/OsReceive/state/OsReceiveState.ts
src/libs/intents/setFlagshipUI.ts

It is meant to be a temporary solution to fix an issue where `resetUIstate`  has to know the state of this feature before executing its logic. Still, at the time of writing, `resetUIState` has no connection to the React tree.
`ResetUIState` should be refactored to use a proper React context.  It can't be done during this commit for time constraints.

fix: handle race condition in resetUiState

---

src/@types/cozy-client.d.ts
src/app/domain/backup/helpers/error.ts
src/app/domain/backup/services/manageBackup.ts
src/app/domain/backup/services/manageLocalBackupConfig.ts
src/app/domain/backup/services/manageRemoteBackupConfig.spec.ts
src/app/domain/backup/services/manageRemoteBackupConfig.ts
src/app/domain/backup/services/uploadMedias.ts

When an user creates a backup, it creates a backup folder like `/Photos/Sauvegardé depuis mon mobile`, and the flagship app saves a reference to this backup folder.
In this PR, I mainly handle missing cases, especially when the user trash or trash + empty trash the backup folder.
Some refactoring too.

Multiple bug fixed when deleting manually backup folder

---

__tests__/jest.config.js
src/App.js
src/components/webviews/CozyWebView.js
src/components/webviews/CozyWebview.spec.js
src/screens/home/HomeScreen.tsx
src/screens/home/components/HomeView.js
src/screens/home/hooks/useLauncherContext.tsx

This is needed to allow mespapiers app to control clisk konnectors.
Also needed to convert launcher context to a global context to allow it
to be used in multiple places (CozyWebView, App)

feat: Move LauncherView to App.js

---

src/app/view/Loading/RemountProgress.tsx
src/components/ProgressContainer.tsx
src/screens/cozy-app/CozyAppScreen.functions.ts

At the time of this commit we know the null value is working,
but it's still a non valid style value.
While not strictly necessary, it would be preferrable to investigate
the source of this behaviour

fix: use `null` value in all animations config

---

src/app/view/Error/ErrorScreen.tsx
src/libs/services/NetService.ts
src/libs/services/NetStatusBoundary.spec.tsx
src/libs/services/NetStatusBoundary.tsx

- Remove direct NetInfo use in NetStatusBoundary (use service instead)
- Add more error handling
- Use hidesplashscreen inside error screen instead of provider
- Refactor waitForOnline to accept callback as function
- Add some comments to clarify flow
All this should clear up conflicting authority issues on online events
NetStatusBoundary handles app mount with the help of NetService.
NetService remains react agnostic collection of functions to be used
by various components inside the application.
Possible improvements would be to have NetStatusBoundary act as runtime
manager of online events instead of having components using netservice
directly. That would require a lot more refactor though and it is not
clear at the moment if it would bring a huge benefit.

refactor: use only one source of online events

---

package.json
patches/react-native-print+0.11.0.patch
src/libs/intents/localMethods.ts
src/libs/intents/printBase64Doc.spec.ts
src/libs/intents/printBase64Doc.ts
src/locales/en.json
yarn.lock

feat: Implement print intent

---

src/components/webviews/jsInteractions/jsLogInterception.ts

when a webview emits a warning log, we get a log which looks like this :
```
LOG  CozyWebView [Console HomeView] w a r n :   % c c o z y - s t a c k
- c l i e n t   D e p r e c a t e d :   i n   n e x t   v e r s i o n s
o f   c o z y - c l i e n t ,   i t   w i l l   n o t   b e   p o s s i
b l e   t o   q u e r y   s e t t i n g s   w i t h   a n   i n c o m p
l e t e   i d
-   Q ( ' i o . c o z y . s e t t i n g s ' ) . g e t B y I d ( ' i n
s t a n c e ' )
+   Q ( ' i o . c o z y . s e t t i n g s ' ) . g e t B y I d ( ' i
o . c o z y . s e t t i n g s . i n s t a n c e ' ) , c o l o r :
```
This fix allows to get a normal display of the logs

fix: Avoid to have deformed webview warning logs

---

package.json
src/libs/Launcher.js
src/libs/Launcher.spec.js
yarn.lock

This option was removed by mistake
Still in draft because expecting https://github.com/konnectors/libs/pull/977 to be merged and will upgrade to the next cozy-clisk version.

fix: Pass the expected log option to saveFiles from cozy-clisk

---

src/app/view/Secure/SetPinView.tsx
src/ui/Button/index.tsx
src/ui/Button/styles.ts
src/ui/Typography/index.tsx
src/ui/Typography/styles.ts

They weren't well adjusted. We have to rationalize quickly
these themes issues.
This commit is more a quick fix.
Some buttons in the app don't use the disabled style some do.
Also we need 1 disabled style per variant per theme (that we use in the
app though).

fix: handle disabled button styles

---

src/app/view/Auth/ErrorTokenModal.tsx
src/app/view/Lock/LockScreen.tsx
src/app/view/OsReceive/OsReceiveScreen.tsx
src/app/view/Secure/PinPrompt.tsx
src/app/view/Secure/SetPinView.tsx
src/components/templates/PromptingPage.tsx
src/libs/icon/IconChangedModal.tsx
src/screens/home/components/ErrorParallelKonnectors.tsx
src/ui/Button/index.tsx
src/ui/Button/styles.ts
src/ui/Container/index.tsx
src/ui/CozyTheme/CozyTheme.tsx
src/ui/TextField/index.tsx
src/ui/TextField/styles.ts
src/ui/Typography/index.tsx
src/ui/Typography/styles.ts
src/ui/colors.ts
src/ui/palette.ts
white_label/brands/cozy/js/ui/palette.ts
white_label/brands/mabulle/js/ui/palette.ts

> [!TIP]
> As usual this PR is meant to be read commit by commit
> Also, to ease reading `styles.ts` files diffs you can hide whitespace diffs
We want the UI to adapt to `normal` and `inverted` themes
Until now we did not support Theming in the UI and we manually applied colors to component based on the expected result (`normal` or `inverted`)
In the IAP feature we will need to reuse the `PromptingPage` component using `normal` theme, but this component is implemented for the `inverted` theme only
So it is time to implement some Theming mechanism
The `CozyTheme` provider will be responsible to enforce a theme (`normal` or `inverted`) to all its children
This provider is inspired by the one on cozy-ui
Then `useCozyTheme` hook can be used on every component and should return the current …

feat: Add CozyTheme provider to handle normal and inverted themes and adapt existing UI

---

src/libs/Launcher.js
src/libs/ReactNativeLauncher.js

And replace it with 'warn'
See cozy/cozy-flagship-app@c6d28d8/src/libs/ReactNativeLauncher.js#L114
for reference
Or else warning messages are displayed as simple log level messages

fix: Remove the use of unexpected 'warning' log level

---

src/app/domain/osReceive/models/OsReceiveState.ts
src/app/view/OsReceive/OsReceiveScreen.tsx
src/app/view/OsReceive/state/OsReceiveState.ts

To avoid screen flashing, always display the screen
if all files in upload queue are in queued status
(meaning no upload started yet)

feat: add new render logic for osreceive screen

---

src/app/view/OsReceive/state/OsReceiveState.ts

```ts
state.filesToUpload.every(
file => file.status === OsReceiveFileStatus.queued
)
```
This returned `true` when given an empty array
Indeed using every() on an empty array will return true

fix: check filesToUpload length before  queue

---

src/app/view/Lock/LockScreen.tsx
src/app/view/Secure/SetPinView.tsx
src/ui/CozyDialogs/ConfirmDialog.tsx
src/ui/CozyDialogs/styles.ts
src/ui/CozyTheme/CozyTheme.tsx
src/ui/Typography/index.tsx

This is needed on screens where we do not have agency in what is displayed on top of the screen. While it may be tempting to use it everywhere for consistency, I believe it's better to rely on the react-native Modal component when possible. This should be used as a last resort where FullWindowOverlay for instance disallow us to display anything above it (on the native UI side).

feat: add new non-native Modal component

---

src/screens/konnectors/LauncherView.js

Also :
- check if the launcher is present
- log a stringified version of the event in konnector log when possible
- or else log stringified version of the event in flagship app console
- apply this same logic to onWorkerError, onPilotError, onPilotWebviewKilled, onWorkerWebviewKilled

fix: Avoid undefined is not a function error in onWorkerError

---

src/app/domain/backup/services/manageRemoteBackupConfig.spec.ts
src/app/domain/backup/services/manageRemoteBackupConfig.ts

Dedup in photo backup means that we do not upload pictures if they already exists in the Cozy.
To identify if two pictures are identical, we compare name and creation date.
For new backup, we compare with our own creation date added in the io.cozy.files metadata. It just works.
But in photo uploaded by old backup, we compare with the creation date that has been taken from EXIF and can  where the timezone could have been badly managed. So if we compare stricly date, it may not work.
So here we compare only part of the date in dedup mode by ignoring the "hour" field :
- its almost impossible to have a false identity by just ignoring the "hour" field => OK
- we can miss some identity => but we accept that our dedup is not 100% accurate

feat(backup): Improve dedup algorithm to work with old backup

---

src/app/view/Lock/useLockScreen.ts

It seems nothing was listening to the backpress anymore.
Fixed that by starting listening to them directly in the view
as it feels safer than listening from a distant service layer

fix: start listening to backpress in lock view

---

src/app/domain/authorization/services/SecurityService.ts
src/libs/RootNavigation.ts

A recent change was getting route name instead of route object.
Thus we didn't have the slug and it was silently failing and
redirecting to home screen when coming back after background mode.

fix: get correct route object in security flow

---

white_label/brands/mabulle/android/app/brand.gradle
white_label/brands/mabulle/ios/CozyReactNative/CozyReactNative.entitlements
white_label/config.json

app scheme and universal link urls were wrong.
the only "mabulle" reference left SHOULD be about the application id
and the application id only ("io.cozy.flagship.mobile.mabulle")
Because we cannot change that one

fix: update scheme android/ios for mabulle (VO-66)

---

src/app/domain/backup/queries/index.ts
src/app/domain/backup/services/manageRemoteBackupConfig.ts

- improve backup dedup performance (10x)
- improve backup dedup readability

Backup dedup performance

---

src/App.js
src/AppRouter.jsx
src/app/domain/authorization/services/SecurityService.ts
src/app/theme/SplashScreenService.ts
src/app/view/Lock/LockScreen.tsx
src/app/view/Lock/LockScreenTypes.ts
src/app/view/Lock/LockScreenWrapper.tsx
src/app/view/Lock/useLockScreen.ts
src/app/view/Lock/useLockScreenWrapper.ts
src/app/view/Secure/PasswordPrompt.spec.tsx
src/app/view/Secure/PasswordPrompt.tsx
src/app/view/Secure/PinPrompt.spec.tsx
src/app/view/Secure/PinPrompt.tsx
src/app/view/Secure/SetPasswordView.tsx
src/app/view/Secure/SetPinView.spec.tsx
src/app/view/Secure/SetPinView.tsx
src/app/view/Secure/hooks/usePasswordPrompt.ts
src/app/view/Secure/hooks/usePasswordProps.ts
src/app/view/Secure/hooks/usePinPrompt.ts
src/hooks/useGlobalAppState.spec.ts
src/hooks/useGlobalAppState.ts
src/hooks/useSplashScreen.ts
src/libs/localStore/storage.ts
src/screens/home/components/HomeView.js

The Lock related screens are responsible to lock the app when it goes to OS background and to display a CTA to the user when their phone is not protected
Previous implementation declared those screens inside of the App's router
This had numerous caveats:
- It was difficult to keep track of when the app would need to be locked
- It was difficult to keep track of where the user was before the app being locked
- For example we needed to wait for the HomeView to be initialized and check if a cozy-app or the OSReceive screen should be displayed to give it to the Lock screen as a context (cf [here](https://github.com/cozy/cozy-flagship-app/blob/master/src/screens/home/components/HomeView.js#L209-L230))
- It was difficult to keep track of when hiding the splashscreen
- If a component was calling …

[VIO-129] feat: Extract Lock related screens from router

---

white_label/brands/mabulle/android/app/src/main/res/values/colors.xml

This had been forgotten in #1101

[VO-170] fix: Set white background on MaBulle Android's bootsplash

---

package.json
src/@types/cozy-flags.d.ts
src/app/domain/backup/services/getMedias.ts
src/app/domain/backup/services/manageAlbums.ts
src/app/domain/geolocation/helpers/quota.ts
src/app/domain/geolocation/hooks/tracking.ts
src/app/domain/geolocation/services/tracking.ts
src/app/domain/limits/checkOauthClientsLimit.spec.ts
src/libs/clientHelpers/createClient.ts
src/libs/intents/localMethods.ts
src/libs/localStore/storage.ts
src/locales/en.json
src/locales/es.json
src/locales/fr.json
yarn.lock

We added a geolocation tracking quota flag that says "you can save for free up to X days of geolocation tracking data". This is the implementation of the flag on flagship app side. 
=> Disable geolocation tracking at startup if quota exceeded and show a notification
=> Return quota status when front end ask for geolocation tracking status

Manage geolocation tracking quota

---

src/app/domain/geolocation/tracking/index.js

Fixes a bug on coachco2 where we enable geolocation, and toggle does not turn on.

fix: startTracking should return only when geolocation tracking has been started or has failed

---

src/app/domain/backup/queries/index.ts
src/app/domain/backup/services/manageAlbums.ts
src/app/domain/backup/services/manageBackup.ts
src/app/domain/backup/services/uploadMedias.ts

Adjust album management with dedup https://github.com/cozy/cozy-flagship-app/pull/1114

Update album for dedup before upload

---

src/app/domain/geolocation/tracking/tracking.js
src/app/domain/geolocation/tracking/upload.js

This allows to start the openpath pipeline after an upload, thanks to a newly deployed API
This will speed up user retrieval of trips, and avoid to execute periodic pipeline for all the users

[DAT-18] feat: Run openpath pipeline after upload

---

src/app/domain/geolocation/helpers/index.ts
src/app/domain/geolocation/services/tracking.ts
src/libs/intents/localMethods.ts

When the user clicks on the "send logs" button in CoachCO2, we want the email's recipient to be autofilled with the Cozy's support email (or the Instance's one if a custom support email is set in the instance's context)
Also in order to ease debugging we want the logs to contain the App's version

[VER-118] feat: Autofill support email when sending CoachCO2 logs and add app's info in the logs

---

src/app/domain/manifest/permissions.ts
src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js

This index is sent only if the konnector has a permission on
io.cozy.files, to avoid unneccessary requests.
This existing files index is needed to have `shouldReplaceFile`
functionnal in konnectors. But shouldReplaceFile won't throw if it is
not present.

feat: Send existing files index to pilot fetch

---

src/app/domain/backup/services/uploadMedias.ts

There are two possibilities to enter the catch in prepareAndUploadMedia :
- with a Promise.reject : must be displayed in logs with JSON.stringify : OK
- with a JS error : must be displayed in logs without JSON.stringify : NOT OK
We should standardize every reject/throw in prepareAndUploadMedia but for the moment, let's just log the error stringified and not stringified.

fix: Display js error when upload fail

---

.env.example
src/libs/httpserver/httpServerProvider.tsx
white_label/config.json
white_label/configure-brand.ts

When simultaneously using two different version of the App (i.e. Cozy app and MaBulle app) then respective HttpServers need to use different HTTP ports
This PR uses the existing `.env` file and `react-native-config` plugin to override the port for each brand

[VO-191] feat: Allow to change HttpServerProvider's default port in white labels

---

src/app/domain/geolocation/helpers/quota.ts
src/app/domain/geolocation/hooks/tracking.ts
src/app/domain/geolocation/tracking/consts.js
src/app/domain/geolocation/tracking/events.js
src/app/domain/geolocation/tracking/index.js

What do you think about this event implementation @Ldoppea and @paultranvan.
It means that we must install "events" package on CozyGPSMemory but that's all.

Check geolocation quota at trip end

---

src/app/domain/iap/services/clouderyOffer.ts
src/app/view/IAP/hooks/useClouderyOffer.ts

This is the last PR for IAP before merging everything
___
**feat: Handle planId parameter in startIap url**
In previous implementation the cloudery did pass only a `productId`
parameter that would contain a `planId` on Android platform
With the new implementation, the cloudery passes the `planId` in a new
parameter in addition to the `productId` that now always contains the
real `productId` on both platforms
This simplifies the `getSubscriptionOffers` method that does not
require a nested map anymore in order to retrieve the missing
`productId`
___
**feat: Add device's language code to Cloudery url when displaying offers**
The stores require us to display localized prices and descriptions to
the user when displaying IAP options
Our understanding is that descriptions and prices should …

feat: Handle `planId` parameter in `startIap` url, pass language code to Cloudery and improve IAP

---

.env.example
.github/workflows/build-android-dev.yml
.github/workflows/build-android-prod.yml
README.md
__tests__/jestSetupFile.js
android/app/build.gradle
android/app/src/main/java/io/cozy/flagship/mobile/MainApplication.java
android/settings.gradle
package.json
src/constants/api-keys.ts
src/libs/client.spec.js
src/libs/clientHelpers/createClient.ts
yarn.lock

Migrate from SafetyNet to Play Integrity (VO-208)

---

package.json
src/app/domain/authorization/services/SecurityService.ts
src/app/theme/SplashScreenService.ts
yarn.lock

It resulted in splashscreen being hidden before the
home webview finished loading

fix: don't hide splashcreen by default on sec flow (VO-197)

---

src/app/domain/geolocation/helpers/index.ts
src/app/domain/geolocation/hooks/tracking.ts
src/app/domain/geolocation/tracking/consts.js
src/app/domain/geolocation/tracking/index.js
src/app/domain/geolocation/tracking/storage.js
src/app/domain/geolocation/tracking/tracking.js
src/app/domain/geolocation/tracking/upload.js
src/libs/localStore/storage.ts

When passing a webhook URL to the pipeline execution request, the server
will request it after its completion.
This webhook is typically the openpath trips fetching. Thanks to this,
we will now be able to retrieve the trips as soon as they are produced.
Related to https://github.com/cozy/coachCO2/pull/370

[DAT-26] feat: Pass stored webhook to pipeline execution 

---

ios/Podfile.lock
package.json
yarn.lock

Last version of cozy-clisk moves cozy-client from deps to peerDeps to avoid conflict with other cozy-client versions. Fix Android build.

feat: Update cozy-clisk

---

.github/workflows/build-android-dev.yml
.github/workflows/build-android-prod.yml

Since January 8 the  `ubuntu-latest` image excludes Android SDKs prior to version 31
By default the `r0adkll/sign-android-release` package uses Android SDK 29. So the build would fail
In order to fix that, we can set the `BUILD_TOOLS_VERSION` env variable to define which version `r0adkll/sign-android-release` should use
Related doc:
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
Related issue: r0adkll/sign-android-release#84
> [!IMPORTANT]
> This seems to also fix the bug we had on `prod` build that would instantaneously crash when opening them on Android devices

[VO-171] fix: Force android tools version on CI when signing APK

---

src/app/view/Lock/LockScreen.tsx
src/app/view/Lock/LockScreenWrapper.tsx

in 9472f4eb4e200a688968d92f7743f4ed08a71577 we fixed a bug on the Lock screen that would display the Home view and the Lock screen side by side on some devices
To fix it we set the Lock screen view with absolute positioning
Since we found the same bug on the SetPin view. We also found that this bug only happens when the keyboard is displayed
This increase our comprehension of the bug as the impacted view seems to all have a `KeyboardAvoidingView` in their tree
We choose to fix the bug higher in the tree view by setting the `LockScreenWrapper` with absolute positioning. This would allow to fix the bug on all Lock related screens
Related commit: 9472f4eb4e200a688968d92f7743f4ed08a71577

fix: Use absolute position for all Lock screens

---

src/hooks/useGlobalAppState.ts

On appStart the homeview will hide the splashscreen
On wakeup, it is more ambiguous so we force it

fix: always hide splashscreen on wakeup (VO-267)

---

src/app/domain/osReceive/models/ShareFiles.ts
src/app/domain/osReceive/services/shareFilesService.ts

We need on the front side to know if :
- share succeeded
- share was canceled
- share failed
So let's not catch everything here.

fix: Do not manage shareFiles errors in flagship app

---

src/libs/services/NetService.ts
src/screens/login/components/ClouderyViewSwitch.tsx

This will avoid a perpetual error state.
We reset the webview state on connection so it doesn't stay stuck

fix: reset cloud webview on connection retrieval (VO-269)

---

src/App.js
src/app/view/IAP/ClouderyOffer.tsx
src/libs/dimensions.ts
src/screens/cozy-app/CozyAppScreen.functions.ts
src/screens/login/components/assets/PasswordView/htmlPasswordInjection.ts
src/screens/login/components/transitions/TransitionToPasswordView.js

This will use the hook return values if possible, otherwise use 24px as default height on Android.
This will remove cases where the dimensions were wrongfully set at the start of the app to be 0, resulting in overlap in statusbar and application
This PR also ensures all getDimensions() call that were at the module level are now moved into the application lifecycle

fix: handle some dimensions race conditions (VO-264)

---

__tests__/jestSetupFile.js
src/app/theme/SplashScreenService.spec.ts
src/app/theme/SplashScreenService.ts
src/app/theme/config.json
src/app/view/Secure/PinPrompt.spec.tsx
src/components/providers/SplashScreenProvider.tsx
src/hooks/useSplashScreen.ts
src/libs/contexts/SplashScreenContext.ts

Due to instability we decide to hide the splashcreen after a set value
(here 15s).
A message will also be sent to Sentry should that error arise.
This is mainly to prevent infinitely stuck splashscreen while the app
below is still functioning

feat: add a timeout for splashscreen (VO-321)

---

src/libs/dimensions.ts

Add a navigation bar height fallback
If getDimensions is called and was going to return a 0 height navbar value, but we also detected the statusBar was 0 (meaning all values are false), then we use the default Android nav bar height as fallback

fix: never return 0 dimensions on Android (VO-305)

---

src/components/webviews/ReloadInterceptorWebView.js
src/components/webviews/SupervisedWebView.js
src/screens/login/components/ClouderyCreateInstanceView.js
src/screens/login/components/ClouderyViewSwitch.tsx

We saw in our log that some requests didn't have the flagship UA. Mostly the ones on the PasswordView:
`
2024-02-06T06:22:02.095Z  200  Mozilla  GET
https://XXX.mycozy.cloud/assets/fonts/Lato-Bold.immutable.woff2 `
It was hard for us to know whether a user had only used the flagship app or not.
So instead of adding the userAgent on each webview, I decided to add it to the SupervisedWebview since each webview rely on it. Like that, if we want to override the props, we can, but by default the flagship UA agent is set.
So I removed all the `applicationNameForUserAgent` that call the SupervisedWebview
I didn't test anything. 

fix: Add by default the flagship UA on SupervisedWebview

---

src/app/domain/backup/services/uploadMedias.ts

Do not stop backup when unknown error. To avoid stopping a huge backup and blocking the user. Error event are already sent to Sentry. 

feat: Do not stop backup when unknown error

---

src/app/domain/geolocation/hooks/tracking.ts
src/app/domain/geolocation/tracking/consts.js
src/app/domain/geolocation/tracking/events.js
src/app/domain/geolocation/tracking/index.js

This code to check geolocation tracking quota at trip end was not working as we want and very difficult to test. Especially local notification was not displayed on iOS in background.
So we decided to remove this trigger of geolocation tracking quota check.

feat: Remove geolocation tracking quota event emitter

---

src/App.js
src/app/theme/SplashScreenService.spec.ts
src/app/theme/SplashScreenService.ts
src/libs/httpserver/indexGenerator.spec.js

This fix introduces several changes in splashscreen failsafe management:
- More logging
- Initial timer on "global" to handle scenarios where no showSplashScreen() are called
- Use a map to allow multiple timers coexisting
- On background handling (delete every timer)
- On active handling (reset timers that existed before going to background to the timeout value, this will allow us to ignore all problems related to unreliable timeout in background mode, remember that these timeout should not be needed in normal circumstances)
Examples
Normal flow:
Going from active to background to active
On this one I had a bug (linked to hot reloading so can't say exactly what happened), but we can still see the timeout managed the issue in the end

fix: handle timeout issues in splashscreen (VO-231)

---

src/app/domain/geolocation/helpers/quota.ts

Changements :
- we use "calendar days" instead of "24h days"
- if remaining days <= 0 instead of remaining days < 0 we disable geolocation
```
* Homogenize quota calculation with coachco2 notification
```

fix: Homogenize quota calculation with coachco2 notification

---

src/app/domain/geolocation/tracking/index.js
src/app/domain/geolocation/tracking/tracking.js
src/app/domain/geolocation/tracking/user.js

```
* Improve tracking logs
*
*
```

Tracking logs

---

.github/workflows/build-android-prod.yml

* This will automatically publish pushed apps in internal track without
the draft status that was previously applied
on all non-cozy apps (was needed at first because GL wasn't
deployed to production yet)

feat: remove draft status when publishing (VO-345)

---

src/screens/login/LoginScreen.js

Without it, we risk destructuring an undefined value

fix: use default empty object in setInstanceData (VO-380)

---

docs/how-to-retrieve-logs-in-release.md
ios/Podfile.lock
package.json
patches/react-native-file-logger+0.4.1.patch
src/App.js
src/app/domain/geolocation/helpers/index.ts
src/app/domain/logger/deeplinkHandler.spec.ts
src/app/domain/logger/deeplinkHandler.ts
src/app/domain/logger/fileLogger.spec.ts
src/app/domain/logger/fileLogger.ts
src/app/domain/logger/supportEmail.ts
src/app/theme/SplashScreenService.ts
src/hooks/useAppBootstrap.js
src/hooks/useAppBootstrap.spec.js
src/libs/localStore/storage.ts
src/locales/en.json
src/locales/es.json
src/locales/fr.json
yarn.lock

In order to allow sending logs whatever if the app is logged or not, or even when the app is stuck on SplashScreen, the easiest way to trigger sending logs is to use deep links
By implementing this, user can now click on `cozy://enablelogs` or `https://links.mycozy.cloud/flagship/enablelogs` links to tell the app to start recording logs into a local file
They can then click on `cozy://sendlogs` or `https://links.mycozy.cloud/flagship/sendlogs` links to trigger the OS send email intent pre-filled with log files and Cozy's  support email
Finally then can click on `cozy://disablelogs` or `https://links.mycozy.cloud/flagship/disablelogs` links to tell the app to stop recording logs
This method is not the most user friendly but it has the advantage to be resilient to UI bugs
We may want to …

[VO-258] feat: Allow to send logs my email after clicking on a deep link

---

src/app/domain/geolocation/tracking/index.js

Allow `startOpenPathUploadAndPipeline` call with no param. This is currently done in the `handleConnectivityChange` method, which was failing because of that.
```
*
* Upload after connectivity failure
*
```

[VER-277] fix: Geolocation upload

---

src/app/domain/geolocation/tracking/index.js
src/app/domain/geolocation/tracking/upload.js

The HTTP error messages were appearing blank in the logs
```
*
* Correctly handle openpath HTTP errors
*
```

fix: Correctly handle openpath HTTP errors

---

src/libs/Launcher.spec.js

These test were really testing ensureKonnectorFolder from cozy-client
and not Launcher.ensureAccountTriggerAndLaunch. And we could get
different results depending on computer locale if the test did not
define proper mocks.
Now these tests test the feature with the proper level
```
* fix Launcher.ensureAccountTriggerAndLaunch test
```

fix: Laucher ensureKonnectorFolder tests

---

package.json
src/App.js
src/app/domain/authorization/services/SecurityService.ts
src/app/theme/SplashScreenService.ts
src/app/view/Lock/LockScreenWrapper.tsx
src/components/providers/RestartProvider.tsx
src/hooks/useGlobalAppState.ts
src/hooks/useNotifications.ts
yarn.lock

On Android, when the app request a restart, the current Activity is not
directly destroyed and the app react as if it was sent to `background`
This triggers the `useGlobalAppState` hooks which shows the
`LOCK_SCREEN` splashScreen
The after the app effectively restarted, it fails to hide all
splashScreens because the `LOCK_SCREEN` one is not expected to be
displayed (but it is)
To prevent this kind of side effects, we want to fully unmount the
components tree, so all hooks would unregister themselves
This PR also fix some hideSplashScreen scenario and improve logs
```
* Update the existing IAP entry with this PR (was not in production yet)
```
___
TODO:

[VO-428] fix: Prevent the app to stuck on SplashScreen after a restart notification

---

src/App.js

In #1137 we implemented a new File logger mechanism
Unfortunately this has a side effect on
react-native-background-geolocation which has a logger mechanism based on the same library and fails to work if we enable our new File logger
A solution is investigated in BeTomorrow/react-native-file-logger#64 but until then we want to disable the feature so we can continue publishing the app
Related PR: #1137
Related Issue: BeTomorrow/react-native-file-logger#64
```
*
*
*
```

fix: Disable File logger

---

package.json
yarn.lock

To get contract destination folders with reference for clisk konnectors
```
* Add contract option to saveFiles
* Proper handling of disk quota exceeded errors
*
```

[SCR-169] feat: Upgrade cozy-clisk to 0.36.1

---

patches/react-native-file-logger+0.4.1.patch
patches/react-native-file-viewer+2.1.5.patch

fix: avoid path provider authority conflict
These two libraries were accessing the default
appname.provider.
It resulted in file-viewer using the configuration of the logger,
the configuration being not compatible, file-viewer was not operable
We decide to fix this issue by using specific
path providers authorities for 
both these libraries, eliminating
the present conflict and avoiding future ones

fix: avoid path provider authority conflict (VO-570)

---

patches/react-native-file-logger+0.4.1.patch
src/App.js

In #1183 we disabled the new File logger mechanism due to a side effect with react-native-background-geolocation
This was because react-native-file-logger would reset all log appenders during initialisation which would prevent native-background-geolocation to work
This commit applies the fix from BeTomorrow/react-native-file-logger#66 (we cannot update the lib as we are still using ReactNative old architecture)
Related PR: #1183
Related issue: BeTomorrow/react-native-file-logger#64
Related issue: BeTomorrow/react-native-file-logger#66

[VO-258] feat: Re-enable File logger

---

src/app/domain/geolocation/tracking/consts.js
src/app/domain/geolocation/tracking/index.js
src/app/domain/geolocation/tracking/tracking.js
src/app/domain/geolocation/tracking/tracking.spec.js
src/app/domain/geolocation/tracking/upload.js
src/app/domain/geolocation/tracking/user.js

```
*
* Prevent missing trips because of overlapping transitions
*
```

[DAT-41] Fix transitions

---

src/libs/httpserver/server-helpers.spec.ts
src/libs/httpserver/server-helpers.ts

Previous regex would inject body classes in the wrong place if the body has no attributes but its child div has class attribute
In that case, the function would inject the classes in the child div classes
With previous regex the following HTML
```html
<html>
<head></head>
<body>
<div class="application"></div>
</body>
</html>
```
Would output
```html
<html>
<head></head>
<body>
<div class="application flagship-app flagship-os-ios flagship-route-home"></div>
</body>
</html>
```
With new regex, it outputs
```html
<html>
<head></head>
<body class="flagship-app flagship-os-ios flagship-route-home">
<div class="application"></div>
</body>
</html>
```
This also fixes a production bug where we found that a `div` with same value for `role` and `class` would see values injected in its `role` …

[VER-421] fix: Correctly inject body classes when `<body>` has no attributes

---

package.json
yarn.lock

If an error happens during a local method call, cozy-intent will log it as a warn log.
```
* If an error happens during a local method call, cozy-intent will log it as a warn log.
```

feat: Update cozy-intent

---

src/app/view/OsReceive/OsReceiveProvider.tsx
src/app/view/OsReceive/state/OsReceiveState.ts

* When uploading files to the app multiple times in a row, the button will correctly show the "next" action instead of the "cancel" one

fix: persist candidateApps in osreceive state (VO-463)

---

patches/react-native-file-logger+0.4.1.patch

In #1187 we fixed the new File logger initialization on Android as it would break the react-native-background-geolocation plugin's internal File logger
This was because react-native-file-logger would reset all log appenders during initialisation which would prevent native-background-geolocation to work
This bug was also present in iOS but appeared latter so we did not notice it and so we did not fix it on initial PR
This commit applies the fix from BeTomorrow/react-native-file-logger#69 (we cannot update the lib as we are still using ReactNative old architecture)
Related PR: #1187
Related PR: #1183
Related issue: BeTomorrow/react-native-file-logger#64
Related issue: BeTomorrow/react-native-file-logger#66
Related issue: BeTomorrow/react-native-file-logger#69
```
*
* Fix a bug that …
```

fix: Correctly initialize File logger on iOS

---

src/libs/ReactNativeLauncher.js

```
* Move saved traceFiles into `Settings/Logs` directory to avoid user confusion about the file presence
```

[SCR-638] feat: Change debug traces save path

---

src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js

```
* Give the list of instance's flags to the context sent to konnectors
```

[SCR-640] feat: Give list of instance's flags to konnectors context

---

package.json
src/app/domain/scanner/services/scanner.ts
src/components/webviews/CozyProxyWebView.js
src/components/webviews/CozyWebView.js
src/libs/intents/localMethods.spec.ts
src/libs/intents/localMethods.ts
src/libs/localStore/sharedMemory.ts
yarn.lock

```
* Add SharedMemory service
```
Related to this PR : https://github.com/cozy/cozy-libs/pull/2540
Merge https://github.com/cozy/cozy-libs/pull/2548 and update cozy-intent

Add SharedMemory service

---

src/libs/Launcher.js
src/libs/Launcher.spec.js

This will prevent the clisk konnectors to redownload files with
multiples bills associated, which can make the execution of clisk
konnector longer, and cause some 409 http errors in logs in those cases.
```
* clisk konnectors: prevent multiple downloads of the same files when multiple bills are associated to the same file.
```

fix: Reindex files between the first call to a saveFiles function and the next (SCR-675)

---

CHANGELOG.md
android/app/build.gradle
ios/CozyReactNative/Info.plist
package.json
src/app/domain/osReceive/models/OsReceiveState.ts
src/app/domain/osReceive/models/ShareFiles.ts
src/app/domain/osReceive/services/OsReceiveApi.ts
src/app/domain/osReceive/services/shareFilesService.ts

With cozy-intent 2.22, local methods receive an option object as first argument. I forgot to update ShareFiles and OsReceive intents. Fixed here.

fix: ShareFiles and OsReceive broken because of intent options

---

src/app/view/OsReceive/OsReceiveScreen.styles.tsx
src/app/view/OsReceive/OsReceiveScreen.tsx

```
* Dark theme for OsReceive screen
*
*
```

fix: Dark theme for OsReceive screen

---

package.json
src/locales/en.json
src/locales/es.json
src/locales/fr.json
src/utils/jsonUtils.spec.ts
src/utils/jsonUtils.ts
white_label/brands/cozy/js/locales/extra-en.json
white_label/brands/cozy/js/locales/extra-es.json
white_label/configure-brand.cmd.ts
white_label/configure-brand.ts

Some languages files were missing translations and also extra languages were not in sync with each other in white labels
Those new checks should ensure that all langages files contain the same keys and that all extra language override the same keys

fix: Add check on language files and add missing translations for en and es files

---

android/settings.gradle

It seems that these two lines are not needed anymore since we updated to React Native 0.72, AGP 7 & Gradle 8.
Error encountered during `./gradlew assembleRelease --no-daemon` : `Reason: Task
':fengweichong_react-native-gzip:copyReleaseJniLibsProjectAndLocalJars' uses this output of task
':@fengweichong_react-native-gzip:stripReleaseDebugSymbols' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.`
```
*
*
* Fail to assemble release due to react-native-gzip
```

fix: Fail to assemble release due to react-native-gzip

---

src/app/theme/colorScheme.ts
src/app/theme/themeManager.ts
src/screens/cozy-app/CozyAppScreen.Animation.tsx
src/screens/cozy-app/CozyAppScreen.functions.ts
src/screens/cozy-app/CozyAppScreen.tsx
src/ui/colors.ts
white_label/brands/cozy/js/ui/colors.ts
white_label/brands/mabulle/js/ui/colors.ts

```
* Remove ui.darkmode.enabled flag condition
```

feat: Remove `ui.darkmode.enabled` flag condition

---

src/constants/strings.json
src/libs/ReactNativeLauncher.js
src/screens/konnectors/LauncherView.js

This feature is still behind the `clisk.automatic.html-on-error` flag
because it still needs some UI work.
When an unexpected error is raised from a clisk konnector, the current
page in the worker is displayed to user and a button to send traces is
proposed which does exactly the same as the `clisk.html-on-error` flag.
```
* Offers the possibility to save html traces on clisk konnector error
```

feat: Allow the user to choose to save debug traces on error (SCR-872)

---

src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js

Clisk konnectors will now be allowed to have multiple accounts for the
same konnector.
To make it possible, the flagship app will allways check that the
sourceAccountIdentifier returned by the konnector, corresponds to the
accountName saved in the account. If there is a difference, it means
that the worker webview is authenticated with the wrong account and it
will ask to the konnector to authenticate again.
If the a wrong sourceAccountIdentifier is return twice, an error is
raised.
```
* Force logout when konnector identifier is different from account name (to allow multi-account for clisk konnectors)
```

feat: Check that the sourceAccountIdentifier corresponds to account name (SCR-869)

---

src/libs/Launcher.js
src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js
src/screens/konnectors/LauncherView.js

Clisk konnectors can now run themselves as server jobs. The result of    the execution is given back to the clisk konnector.
This is just a first step. Later, it will be possible to let hybrid
konnector be run only in server mode when the context is relevant.
```
* Allow clisk konnectors to save data in their own account
* Allow clisk konnectors to run server job
* Allow clisk konnectors to have incognito mode
```

feat: Allow clisk konnectors to run server job (SCR-845)

---

android/build.gradle
ios/Podfile.lock

androidx.annotation:annotation:1.9.1 breaks our build, maybe because of kotlin version
See https://developer.android.com/jetpack/androidx/releases/annotation#1.9.1
Leading to errors like this :
```
Execution failed for task ':app:mergeExtDexDevDebug'.
> Could not resolve all files for configuration
':app:devDebugRuntimeClasspath'.
> Failed to transform annotation-jvm-1.9.1.jar
```
```
*
*
*
```

fix: Build broken by androidx.annotation

---

src/@types/cozy-client.d.ts
src/App.js
src/app/domain/authentication/services/BiometryService.spec.ts
src/app/domain/authorization/services/LockScreenService.spec.ts
src/app/domain/io.cozy.files/importantFiles.ts
src/app/domain/io.cozy.files/offlineFiles.spec.ts
src/app/domain/io.cozy.files/offlineFiles.ts
src/app/domain/io.cozy.files/offlineFilesConfiguration.ts
src/app/domain/io.cozy.files/remoteFiles.ts
src/app/domain/settings/services/SettingsService.spec.ts
src/app/view/Secure/PinPrompt.spec.tsx
src/hooks/useGlobalAppState.spec.ts
src/libs/intents/localMethods.spec.ts
src/libs/intents/localMethods.ts
src/libs/localStore/storage.ts

When the application is offline, we want the user to be able to access their files that are accessible offline
To make this possible, we want the Flagship app to provide a new `downloadFileAndPreview()` interface that can be called from cozy-apps
Internally this method should allow to download and preview files, but also to store them in the device's storage in order to make them accessible later even when the app is offline
This method will be called from cozy-client through `file` model
For now we make files accessible only if they have already downloaded
once
___
We also want the user's important files to always be accessible offline
To make this possible, we want the app to download them in background on startup
We consider important files as files from `mespapiers` with specific …

feat: Allow cozy-apps to access files offline

---

src/App.js
src/components/webviews/CozyProxyWebView.functions.js
src/components/webviews/CozyProxyWebView.js
src/libs/httpserver/httpServerProvider.tsx
src/libs/httpserver/indexGenerator.ts
src/libs/httpserver/models.ts
src/locales/en.json
src/locales/es.json
src/locales/fr.json

`NetStatusBoundary` is used to display an `offline` error screen when
the app is offline
Now that we implemented offline mode, we now want to disable the
`NetStatusBoundary` for cozy-apps as they should now be accessible when
offline
`NetStatusBoundary` is kept only on onboarding screens
__
In iOS, we disabled HttpServer for all cozy-apps as the WebView API may
behave differently
The side effect is that we cannot open those app when offline as we
cannot inject minimal code to make them work without network access
So we want to enable HttpServer on those apps when we detect the app to
be offline
Related PR: #486

feat: Correctly handle error screens when the app is offline and allow to open cozy-apps when offline in iOS

---

src/app/domain/offline/isOfflineCompatible.ts
src/libs/httpserver/httpServerProvider.tsx

When offline, we want to open coz-apps only when they declare to be compatible with Offline mode
Cozy-app can declare this by setting `offline_support: true` in their manifest.webapp file
Non compatible cozy-app won't be opened when the Flagship app is offline, and instead an error message will be displayed

feat: Open cozy-app when offline only if it supports Offline mode

---

docs/how-to-make-cozy-app-offline-compatible.md

This PR documents how to make a cozy-app compatible with Offline mode

docs: Document how to make a cozy-app compatible with Offline mode

---

src/libs/intents/flagshipLink.ts

`io.cozy.jobs` take very long time to be queried when using a local PouchDB
This commit early return an empty array of jobs instead of actually doing the query so we can display cozy-home faster until we find a better solution

fix: Skip io.cozy.jobs queries

---

__tests__/jestSetupFile.js
ios/Podfile.lock
package.json
src/pouchdb/sendDbByEmail.ts
yarn.lock

In previous commit we implemented a mechanism to send DB files by email
as attachments
This would not work because DB files may be bigger than most common
email providers' size limit
So instead of sending them as attachment, we now upload them in the
Cozy, we create a sharing link and then we send this sharing link by
email
The folder used for the upload is `Settings/AALogs/<datetime>`

fix: Upload DB files to the Cozy instead of sending them by email

---

src/components/webviews/jsInteractions/jsLogInterception.ts

- Support console.group and console.groupEnd
- Log an message instead of throwing for console.count, console.countReset, console.table, console.time and console.timeEnd which are unsupported by cozy-minilog and/or react-native
group/groupEnd example on React Native metro
group/groupEnd example on the webview
```
*
*
* Improve log interception
```

feat: Improve log interception

---

src/app/domain/backup/services/manageLocalBackupConfig.ts
src/app/domain/backup/services/manageRemoteBackupConfig.ts

Due to the way we manage errors, we sometimes try to JSON.parse string that were not JSON leading to errors like "[SyntaxError: JSON Parse error: Unexpected character: N]" displayed to the user.
Now we use the try/parse pattern to return the most appropriate message to the user.
```
*
* Improve error message when query fail in  backup
*
```

fix: Improve error message when query fail in  backup

---

src/app/domain/backup/services/uploadMedia.ios.ts

```
*
* Video not uploaded by backup on iOS 18
*
```

fix: Video not upload by backup on iOS 18

---

src/libs/ReactNativeLauncher.js
src/libs/ReactNativeLauncher.spec.js

In ensureAuthenticated method, clisk konnectors now also get current
trigger when available.
```
* clisk: ensureAuthenticated get trigger when available
```

feat: Allow clisk konnectors to have more context

---

android/app/src/main/java/io/cozy/flagship/mobile/MainApplication.java
ios/Podfile.lock
package.json
src/App.js
src/app/domain/logger/fileLogger.spec.ts
src/libs/localStore/clientCachedStorage.spec.ts
src/libs/localStore/clientCachedStorage.ts
src/libs/localStore/storage.ts
src/pouchdb/platformReactNative.storage.ts
src/redux/store.ts
yarn.lock

Since we migrated the project to RN73 we can now use MMKV instead of AsyncStorage
This migration is done in order to improve performances. MMKV being faster by multiple order of magnitude than AsyncStorage
This PR replaces #1097
```
*
*
* Migrate storage management from AsyncStorage to MMKV
```

feat: Migrate storage from AsyncStorage to MMKV

---

src/app/domain/authentication/services/AuthService.ts
src/app/domain/authentication/services/SynchronizeService.spec.ts
src/app/domain/authentication/services/SynchronizeService.ts
src/app/domain/io.cozy.files/importantFiles.ts
src/hooks/useAppBootstrap.js
src/pouchdb/getLinks.ts

This PR's goal is to improve startup timings by delaying heavy tasks after the startup is complete.
What have been delayed:
- PouchDB replication
- Important files downloading (for offline access)
- Call to Oauth client's `synchronize()` api
- Downloading of cozy-app icons for opening animations
For now those delay have been hardcoded, but in the future we may want to implement some "orchestrator" mechanism that would be responsible to call those tasks when the application is IDLE
```
* Improve startup timings
*
*
```

feat: Optimize startup timings by delaying heavy tasts

---

src/App.js
src/libs/services/NetService.ts
src/pouchdb/platformReactNative.isOnline.ts

This PR add caching for the `isOnline()` method and also change the way NetService is initialized to prevent unwanted calls to google's servers
```
*
*
*
```

feat: Optimize NetService related performances

---

src/app/domain/io.cozy.files/importantFiles.ts
src/app/domain/io.cozy.files/offlineFilesConfiguration.ts

Previous implementation was incorrect because `lastOpened` prop was stored as a string in the device's storage and so it was retrieved as string
Then the date-fns `differenceInMonths` was failing comparing dates as it accepts only `Date` objects and no string
This commit fixes this by parsing the persisted date into a `Date` and by fixing related TS typings

fix: Correctly handle removal of unimportant cached files

---

src/libs/localStore/storage.ts

feat: Remove old hack for DefaultRedirectionUrl migration

---

package.json
src/@types/cozy-client.d.ts
src/App.js
src/app/domain/authentication/services/AuthService.ts
src/app/domain/offline/hooks/useOfflineReplicationOnRealtime.ts
src/app/domain/offline/utils.ts
src/hooks/useGlobalAppState.ts
src/libs/client.js
src/libs/clientHelpers/createClient.ts
yarn.lock

With previous PouchDB/offline implementation, the app was able to trigger a full replication on application's startup, but then nothing would be replicating until next app's restart
This PR is responsible to implement 2 new scenario:
- When the app goes to background and then come back to foreground, then we trigger a replication
- When the app receives a realtime event from one of the CozyPouchLink's configured doctypes, then we trigger a replication
For both scenario, the replication is debounced for 30s with a maximum of 10min

feat: Trigger replication on appstate changes and realtime events

---

src/libs/client.js
src/libs/clientHelpers/createClient.ts

CozyClient.registerPlugin typing requires an `option` parameter to be defined
But the RealtimePlugin expect this parameter to be optional or to be an object
If `null` is given, then the application would crash. We injected `null` in #1279 because the CI did reject the initial attempt with no parameter, but this was not the correct solution, the correct one would be to inject an empty object
In the future we may want to make this parameter optional in the `registerPlugin` definition
- cozy/cozy-libs#2703 (this is a beginning but this don't fix the declaration on cozy-client's side)

fix: Inject `{}` instead of `null` as second parameter of RealtimePlugin

---

package.json
src/app/domain/search/search.ts
yarn.lock

In cozy/cozy-libs#2720 we added PerformanceAPI in the SearchEngine
This commit reflect the changes to the SearchEngine constructor
Related PR: cozy/cozy-libs#2720

feat: Add performance measurement capabilities to SearchEngine

---

src/app/domain/authorization/services/LockScreenService.spec.ts
src/app/domain/authorization/services/LockScreenService.ts
src/libs/client.js

When implementing the offline support, we did test the unlock screen using the PIN code
But we found that the Unlock by Password mode would require internet access in order to retrieve the number of KDF iterations for hashing the password
By caching this method's result, we allow this method to retrieve the number of KDF iteration even when offline
We also found that the Unlock by Password mode would require internet access in order to verify the password on the cozy-stack side
By nature this is impossible to do when offline, and we already check the entered password against the one stored in the phone's keychain
So we want to make this method resilient to connectivity issues
When disconnected, the app will now only checks the password agains the hash stored in the local keychain

fix: Allow Unlock by Password feature when offline

---

.github/workflows/build-android-dev.yml
.github/workflows/build-android-prod.yml
.github/workflows/build-ios-dev.yml
.github/workflows/build-ios-prod.yml

We are not concerned by breaking changes. See https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
It seems we need https://github.com/cozy/cozy-flagship-app/pull/1253/commits/3eff0bd3182cab350ca12d88647db6103cb1679b.
```
*
*
* Update actions/upload-artifact to v4
```

chore: Update actions/upload-artifact to v4

---

src/libs/defaultRedirection/defaultRedirection.spec.ts
src/libs/defaultRedirection/defaultRedirection.ts

To compute the home redirection link at startup, we query the instance settings doc to extract the `default_redirection` attribute. However, we were using the `data.attributes` object to access it, which cannot work in offline, because there is no JSON-API formatting coming from PouchDB. And it is not required with online, because cozy-client does the JSON-API normalization.
```
*
* Get correct redirect link with offline 
*
```

fix: Redirection is not properly working in offline

---

ios/CozyReactNative/Info.plist

To be able to open these apps from flagship app in iOS. Goal is to have the same behavior as Cozy Pass for Cozy Twake Chat and Cozy Twake Mail : 
- they will be displayed on the Home
- on browser we can open them as Cozy apps
- on mobile it redirects to native apps
```
*
*
* Add Twake apps queries schemes
```

feat: Add Twake apps queries schemes

---

ios/Podfile.lock
package.json
patches/react-native-file-logger+0.6.0.patch
src/app/domain/logger/fileLogger.spec.ts
src/app/domain/logger/fileLogger.ts
src/app/domain/performances/sendPerformancesByEmail.ts
src/app/domain/supportEmailer/sendEmail.ts
src/app/domain/supportEmailer/temporaryFile.ts
src/app/domain/supportEmailer/uploadFiles.ts
src/pouchdb/sendDbByEmail.ts
yarn.lock

The goal of this PR is to fix a bug that prevented to correctly write logs into the log files on Android (see https://github.com/BeTomorrow/react-native-file-logger/issues/68).
Also we improved the log sending process in order to upload the file on the Cozy instance before sending them by email. This would allow to retrieve the files even when the email intent fails to open.
However, when no Cozy is logged-in, then we still use the old "email only" scenario.

fix: Upload log files to the Cozy instance before emailing them + fix the react-native-file-logger that failed to write logs in the files

---

package.json
yarn.lock

Due to the removal of geolocation libraries in #1283 we encountered some dependencies bug in the react-native-gzip library
This new version should fix those issues
Related PR: cozy/react-native-gzip#4

feat: Upgrade Cozy's react-native-gzip to 1.2.0

---

src/pouchdb/sendDbByEmail.ts

Somewhere in the previous Offline related changes, we changed where the Pouch database are stored, which broke the emailing process

fix: Correctly send Databases by email when using universal link

---

src/libs/httpserver/indexGenerator.ts
src/pouchdb/getLinks.ts

This PR declares the Papillon related doctypes needed for offline replication and allows Papillon app to use local HTTP server on iOS

feat: Allow to use Papillon while offline

---

.github/workflows/build-ios-dev.yml
.github/workflows/build-ios-prod.yml
ios/Podfile

Apple now requires apps to be build using iOS18 SDK

fix: Make the CI builds target iOS 18

---

package.json
src/screens/login/LoginScreen.js
src/screens/login/components/TwakeCustomServerView.tsx
src/screens/login/components/TwakeWelcomeView.tsx
src/screens/login/components/typedefs.js
yarn.lock

When clicking on `Use your company server` button, we wan't to be able to either:
- login to old Cozy instances (already implemented)
- login to OIDC instance (to be implemented)
This commit implement the detection of the login mechanism (classic vs OIDC)
Then for OIDC instances, in implements the login mechanism. To make this login work, we use the `client.authorize()` mechanism that already implement in-app-browser based authorisation scenario that is able to redirect to the OIDC portal if detected. This redirection is handled by the cozy-stack

feat: Implement OIDC login for new Twake scenario

---

src/libs/localStore/storage.ts

In previous implementation we did not clear all the non-device persisted data on Logout
Some of them were created by cozy-pouch-link and were not listed here so they were ignored by the clear process (and so the pouch replication process would be broken after switch cozy's instances)
To prevent this in the future, we change the algorithm to clear ALL the persisted data except the device ones

fix: Clear all non-device persisted data on logout

---

src/locales/en.json
src/locales/es.json
src/locales/fr.json
src/screens/login/components/TwakeCustomServerView.tsx
src/screens/login/components/TwakeWelcomeView.tsx
src/screens/login/components/functions/autodiscovery.ts

When using a company server, your previously needed to enter your Twake instance link which is not very user friendly.
Here we homogenize the behavior with our other apps (see https://github.com/cozy/cozy-pass-mobile/pull/104 and https://github.com/cozy/cozy-keys-browser/pull/359) with an autodiscovery mechanism based on a .well-known file so that we can only ask the company email.
We keep the login by url feature as a backup.
```
* Login by email when using a company server
```

SSO by email for company server
